In [82]:
import pandas as pd
import json
from bs4 import BeautifulSoup

In [83]:
df = pd.read_csv("../data/pseudo_json_dataset_V3_2048.csv")

In [84]:
index_df = pd.read_csv("../data/index_info.csv")

In [85]:
index_df.head()

,Index of data without headers,Index of data with multiple headers,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,1,692.0,NaN,NaN,
1,36,712.0,NaN,NaN,NaN
2,60,NaN,NaN,NaN,NaN
3,90,NaN,NaN,NaN,NaN
4,111,NaN,NaN,NaN,NaN

In [86]:
indexes = index_df['Index of data without headers'].tolist()

In [87]:
df.head()

,answer,html_content,index,question,pseudo_json_encoding
0,1.5% ( 1.5 % ),<html>\n <body>\n visa inc . notes to consoli...,1534,What is risk-free rate of return ( 2 ) for 2015 ?,<html>\n<body>\n visa inc . notes to consolid...
1,3568,<html>\n <body>\n notes to consolidated finan...,988,What is credit funds2 for unfunded commitments ?,<html>\n<body>\n notes to consolidated financ...
2,28649,"<html>\n <body>\n hologic , inc . notes to co...",618,What is net income for 2006 ?,"<html>\n<body>\n hologic , inc . notes to con..."
3,7450.4,<html>\n <body>\n page 31 of 98 additional de...,1077,What is purchase obligations ( c ) for payment...,<html>\n<body>\n page 31 of 98 additional det...
4,$2492,<html>\n <body>\n vertex pharmaceuticals inco...,1531,What is discretionary matching contributions d...,<html>\n<body>\n vertex pharmaceuticals incor...

In [88]:
df.shape

(17538, 5)

In [89]:
index_df = pd.read_csv("../data/dataset_index.csv")
index_df.head()

,html_content,questions,index
0,"<html>\n <body>\n ""distribution date"" ) . unt...",['what was the percentage of the total common ...,1
1,"<html>\n <body>\n ""three factor formula"" ) . ...","['in the year of 2013, during the second quart...",2
2,"<html>\n <body>\n $ 25.7 million in cash , in...","['in the year of 2009, how much did the income...",3
3,<html>\n <body>\n $ 43.3 million in 2011 comp...,['what was the difference between the net sale...,4
4,<html>\n <body>\n ( $ 125 million ) and highe...,['what were north american industrial packagin...,5

In [90]:
for i, row in df.iterrows():
    try:
        if isinstance(eval(row['answer']), list):
            df.drop(i, inplace=True)
    except:
        print(row['answer'])

1.5% ( 1.5 % )
$2492
$186.16
$ -
3.4% ( 3.4 % )
$311
$24490
$77.15
-228 ( 228 )
$971
$838
$5524
-1 ( 1 )
$73
$81.21
55.6% ( 55.6 % )
-2.8 ( 2.8 )
$2554.70
$17.40
-76 ( 76 )
-3020 ( 3020 )
$728979
50% ( 50 % )
$20941
$82.42
$6241
$65759
$124176
$54.00
$2235
( 16% ( 16 % ) )
$1312
$ -5123 ( 5123 )
-2352 ( 2352 )
-146 ( 146 )
wind
-0.9 ( 0.9 )
-44 ( 44 )
-42.2 ( 42.2 )
-12 ( 12 )
$136.62
-24 ( 24 )
15.0% ( 15.0 % )
$1636
$972.90
-186742 ( 186742 )
$5245
4.1% ( 4.1 % )
-5.1 ( 5.1 )
$100.20
-5965 ( 5965 )
2.45%-2.90% ( 2.45%-2.90 % ) above 3-month libor
$170.50
$980
-32 ( 32 )
-2046 ( 2046 )
1.7% ( 1.7 % )
-1308 ( 1308 )
-293.2 ( 293.2 )
-
-52421 ( 52421 )
-155 ( 155 )
-96.9 ( 96.9 )
-14 ( 14 )
11.8% ( 11.8 % )
$75
$1240
-1367 ( 1367 )
-1.2 ( 1.2 )
-14623 ( 14623 )
$103.50
$ 124 million
$159
-94 ( 94 )
$116
$5064
leased
$599
$430.90
$439
-896 ( 896 )
-34.2 ( 34.2 )
$60.17
$524340
$2739
-45 ( 45 )
-9 ( 9 )
-165 ( 165 )
4.6% ( 4.6 % )
expiring in 2010
$1925
$463000000
-306 ( 306 )
-3 ( 3 )
-127.7 ( 127.7 )
$ -97 ( 97 )
$4134155
$189.45
-15.1 ( 15.1 )
0% ( 0 % )
838 mw - boiling water
$ -30 ( 30 )
$1934232
$163.60
$155.80
-9049 ( 9049 )
$28.40
-
-27 ( 27 )
trading floor and office space
-61 ( 61 )
9.3% ( 9.3 % )
$1905
-
-134 ( 134 )
26% ( 26 % )
$603
-120016 ( 120016 )
-888 ( 888 )
$4372
-22 ( 22 )
-138 ( 138 )
-6 ( 6 )
-1092 ( 1092 )
nashville tn
$81
$253
4.29% ( 4.29 % )
-1.9 ( 1.9 )
$77
$ -35 ( 35 )
-94 ( 94 )
2.4% ( 2.4 % )
$11.70
$9.84
-1455 ( 1455 )
$100.00
-70829 ( 70829 )
$490000000
$2573
$322.20
$76.74
$118.21
$18
26% ( 26 % )
-104 ( 104 )
$6380
$90
-45.4 ( 45.4 )
$1370
$ -15364 ( 15364 )
$13219
-159 ( 159 )
$2014
$199120
$3043
-199.1 ( 199.1 )
$807
2014% ( 2014 % )
-288 ( 288 )
$108
-482 ( 482 )
$7.28
-2538 ( 2538 )
-33.2 ( 33.2 )
56.3% ( 56.3 % )
$5642
27.3% ( 27.3 % )
3.15% ( 3.15 % )
-1602 ( 1602 )
$6530
$1529.80
3.0% ( 3.0 % )
-12315 ( 12315 )
$7315
$84313
2015 ccg operating income
1.8% ( 1.8 % )
$225.85
$1370
$8.20
-2194 ( 2194 )
$173.87
$555
$63647
-14 ( 14 )
-32.0 ( 32.0 )
$19111
$3685
$39
-394 ( 394 )
$0.00
-530 ( 530 )
$1745
-2 ( 2 )
$1251628
$468.00
( 1 ) % ( % )
$201557625
$892
$11.09
$12543
$164
27.3% ( 27.3 % )
$182268
--
$32452
-18 ( 18 )
$102
$ -1046 ( 1046 )
$ -66.5 ( 66.5 )
-1151 ( 1151 )
$11473
$3749
$42335
( in thousands )
$139.60
$26.66
-29191247 ( 29191247 )
$1045.90
-80258 ( 80258 )
-769 ( 769 )
-49 ( 49 )
-712 ( 712 )
$1800
$10
$4546
$110
$31009
-387 ( 387 )
-5 ( 5 )
-12 ( 12 )
-15119 ( 15119 )
-63624 ( 63624 )
-4423 ( 4423 )
-1225 ( 1225 )
$14920
-0.2 ( 0.2 )
$255681
60% ( 60 % )
$27.50
$176138
-222 ( 222 )
$908
$146761
$1977
$337226
$525
-50 ( 50 )
$ -22.0 ( 22.0 )
26.16% ( 26.16 % )
$2350
$1396.50
$570
$209
-1.3 ( 1.3 )
$51
-1047 ( 1047 )
$11529
$151
$156.77
$ -47 ( 47 )
$119
$106.20
$407
$23.20
-156 ( 156 )
$144.65
$159819370
-2 ( 2 )
$245
-5.5 ( 5.5 )
coal
4.5% ( 4.5 % )
$262722
-20 ( 20 )
$825
87.4% ( 87.4 % )
$127
$15248
-80.0 ( 80.0 )
$5654
4.4% ( 4.4 % )
-35 ( 35 )
$301
$25.22
buchanan ny
-12353 ( 12353 )
$ -2520 ( 2520 )
$2217.60
-47.8 ( 47.8 )
$1970
$3220.90
$ 5.5 million
$107.59
-1.2 ( 1.2 )
$0.18
( 1.2 ) % ( % )
-
$1890.10
85.8% ( 85.8 % )
$168872
1.4% ( 1.4 % )
-12 ( 12 )
35% ( 35 % )
$32768
$22171
-29202 ( 29202 )
( in thousands )
7.5% ( 7.5 % )
3.884% ( 3.884 % )
-154.0 ( 154.0 )
-43 ( 43 )
higher ccg platform unit costs
-223 ( 223 )
$150.50
$4067
-15.9 ( 15.9 )
-81 ( 81 )
$61
$18.16
$477
$ 310 million
-5577 ( 5577 )
$4273
-2396 ( 2396 )
$487
40% ( 40 % )
16% ( 16 % )
36.23% ( 36.23 % )
9.5% ( 9.5 % )
$2685
$104.23
$37.40
-103 ( 103 )
$152.60
2.00% ( 2.00 % )
-1759 ( 1759 )
$747
6.9% ( 6.9 % )
-1197 ( 1197 )
$15.90
$116.56
$7371
-61871 ( 61871 )
$644.20
$459.67
$49
$187
$2175.10
$85.70
$151688

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$18.50
25% ( 25 % )
$265853
$135
$19
2017 2013 2024
$24412
-11.0 ( 11.0 )
-596.6 ( 596.6 )
$509
$57
trading floor and office space
$ -4.34 ( 4.34 )
$44.16
$1807
$ 2.4 billion
$5873
( 8 ) % ( % )
$377
-4 ( 4 )
$271.40
$20684
$ -1422 ( 1422 )
$33
$150
$8091
-.1 ( .1 )
-1050 ( 1050 )
$39.38
$401.40
-96.1 ( 96.1 )
$71267
$53624809
$1802
2031 ( 5 )
-
$28.86
$13373
$7729
$218620420
-5.2 ( 5.2 )
-1273119 ( 1273119 )
64.8% ( 64.8 % )
owned
38.6% ( 38.6 % )
$205.95
$801250
$183
$ 75 million
-33.1 ( 33.1 )
-1 ( 1 )
-593 ( 593 )
$15
$1639040
-6846 ( 6846 )
$43
various
$2336
$7525
4.0% ( 4.0 % )
0% ( 0 % )
9.60% ( 9.60 % )
-5 ( 5 )
-9 ( 9 )
$2800
$4039
37.11% ( 37.11 % ) 2013 37.48% ( 37.48 % )
-741 ( 741 )
$449.90
$109.30
-227 ( 227 )
0.8% ( 0.8 % )
$58
$14.30
-2816 ( 2816 )
-335360 ( 335360 )
-587 ( 587 )
1.6% ( 1.6 % )
-
$1.67
$2329053
$122.80
$7457
$12440
$68
$4213
-876 ( 876 )
$37899
-23359 ( 23359 )
$2013
-
-4 ( 4 )
$110
-4 ( 4 )
$9244.90
$274.01
-936.5 ( 936.5 )
$60.78
-919 ( 919 )
$12.06
nan
-52 ( 52 )
$128.21
$1425
$103.73
$2014
$81
-1631 ( 1631 )
$206852
-67 ( 67 )
$2320.70
$150.97
-5 ( 5 )
$1847.80
$1203
-5915 ( 5915 )
$4037
$307833
-24 ( 24 )
$166
$35603
$77.38
69.5% ( 69.5 % )
$20.50
-4 ( 4 )
$132.38
30% ( 30 % )
-1 ( 1 )
3.00%-3.30% ( 3.00%-3.30 % ) above 3-month libor
$92116
-128 ( 128 )
$1791.80
$16832
$153.90
$59765
-10.2 ( 10.2 )
$663750
-136 ( 136 )
-21.9 ( 21.9 )
40.2% ( 40.2 % )
$387
$103043
-524 ( 524 )
$162.82
hydro
$103102
-1034 ( 1034 )
$54.89
-93 ( 93 )
$8367
$4.75
$403.70
$1565518
-19 ( 19 )
$79
$285
$6813
$145
$195.80
$171
$604
-130 ( 130 )
$95
$719
-33 ( 33 )
$70
$2450
-91.3 ( 91.3 )
$1.80
$ 2.7 billion
-17 ( 17 )
-45.4 ( 45.4 )
-322 ( 322 )
$162
-1.4 ( 1.4 )
$858
-30 ( 30 )
< 1
$431418
17.78% ( 17.78 % )
$10.50
$ -55 ( 55 )
$121.13
$50.33
$0.11
$ -325321 ( 325321 )
us-wv
4.1% ( 4.1 % )
$129
33.2% ( 33.2 % )
$78975
$100.00
-35 ( 35 )
-7.5 ( 7.5 )
-156 ( 156 )
-360734 ( 360734 )
$27.32
July 31 2014
-22.6 ( 22.6 )
$214
-10 ( 10 )
$88472
1.4% ( 1.4 % )
$1011.80
November 30 2039
$4376
$335
$52
$60.05
$946848
-3.0 ( 3.0 )
-114000 ( 114000 )
-
-10033.2 ( 10033.2 )
-8 ( 8 )
$42725
4.99% ( 4.99 % )
leased
$100.00
22% ( 22 % )
-11672 ( 11672 )
$1508
$626.29
$72.41
1041 mw - pressurized water
-10 ( 10 )
$1829
April 1 2020
2.8 years
-47 ( 47 )
$ 2.4 billion
Nov . 2000
$1.49
$5554
$122
-8 ( 8 )
$500.70
35.0% ( 35.0 % )
$500.00
$ -2310 ( 2310 )
-
$52.00
$2778
$2050
-14.6 ( 14.6 )
$100
$2014
$14212
$229
-42.2 ( 42.2 )
$171.77
$14171.80
$5680
$248
-11766 ( 11766 )
coal
-38.0 ( 38.0 )
$20963
$2012
75.3% ( 75.3 % ) - 79.2% ( 79.2 % )
-6948 ( 6948 )
$477
$36033
-11333 ( 11333 )
$15486
$0.10
25% ( 25 % )
1.4% ( 1.4 % )
$727
-7135 ( 7135 )
-533 ( 533 )
-25.7 ( 25.7 )
$971
$249440
-1102 ( 1102 )
$384
2.1% ( 2.1 % )
$7788
$619
-710 ( 710 )
$701.20
$100
$10630
$195
4 years
$9105
2.50% ( 2.50 % )
$619373
$106
$13.25
$1922
4.00 years
$18.80
$18508
-662 ( 662 )
$4267375081
$690.60
$51.59
$553
-30.6 ( 30.6 )
global supply chain distribution and administration offices
-4.9 ( 4.9 )
-37375 ( 37375 )
$101
67.1% ( 67.1 % )
$6306
-78 ( 78 )
$494
$21.30
-21604 ( 21604 )
$13203
$8137
20.4% ( 20.4 % )
1.1% ( 1.1 % )
$26.69
$372863
-0.4 ( 0.4 )
$3067.80
$870
$205
-93 ( 93 )
$109.88
$3671
poland
-179 ( 179 )
$907.40
5.01% ( 5.01 % ) 20145.17% ( 20145.17 % )
$2014
$3710
-
$3739
$12.44
-210.2 ( 210.2 )
$1250
-14.7 ( 14.7 )
-3279 ( 3279 )
$0.52
$170.50
5 years
-78 ( 78 )
40.1% ( 40.1 % )
owned
$113.41
-2491.5 ( 2491.5 )
-1408 ( 1408 )
$11
$2666
-0.7 ( 0.7 )
-24.9 ( 24.9 )
nan
$148
17.7% ( 17.7 % )
-1 ( 1 )
cash/charitable contribution
-14 ( 14 )
$409201
$2014
$7680
( 13 ) % ( % )
$100
$25.10
-583.8 ( 583.8 )
total gains or losses ( realized /unrealized )
$166
-
0.07% ( 0.07 % ) 2013 0.13% ( 0.13 % )
$611.90
$9083
$707
$2732
-36 ( 36 )
-27 ( 27 )
$21579
-905 ( 905 )
$100.98
-8 ( 8 )
$15.00
$1973
class c ( series ii )
$143400
( 1.1% ( 1.1 % ) )
1.1% ( 1.1 % )
$213
87.2% ( 87.2 % )
$6415
17.23% ( 17.23 % )
-797 ( 797 )
$5367
$12944
$225104
$550
$133
$162.81
$1041861
commercial research and development manufacturing
$ -1222 ( 1222 )
-22 ( 22 )
$2644
$6189
$13463
-
$5777
$1355605
$2246.10
$37.84
-105 ( 105 )
-9010 ( 9010 )

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$70.48
$24.07
$110
-1213 ( 1213 )
$47.59
55% ( 55 % )
25.2% ( 25.2 % )
$433226
-9379 ( 9379 )
$72
$529
-6.5 ( 6.5 )
-183 ( 183 )
$2422
$1890.80
$90.29
$132.90
$7463
$4457
$235.63
$3624
-3.6 ( 3.6 )
-70 ( 70 )
nan
-6 ( 6 )
$100.00
$36.61
$100.00
$122.64
is0-ne
-504 ( 504 )
$1173
-
lower production costs primarily on our 14nm products treated as period charges in 2014
$180149
-23 ( 23 )
$8.90
$229
-95329 ( 95329 )
-1677 ( 1677 )
$927
$163.71
$95.70
-11.5 ( 11.5 )
owned
-147 ( 147 )
$51.66
-489 ( 489 )
hydro
-.5 ( .5 )
-35 ( 35 )
$121
17.40% ( 17.40 % )
$4130
0.8% ( 0.8 % )
-5.4 ( 5.4 )
-12 ( 12 )
leased
( 0.4 ) % ( % )
$ -1.56 ( 1.56 )
$977400
$2.60
-11093 ( 11093 )
-39218 ( 39218 )
-21 ( 21 )
-36 ( 36 )
$509
$7280
$4044
-
$18
-29.4 ( 29.4 )
$0
$104.05
-41.2 ( 41.2 )
$148.55
$7.96
-310 ( 310 )
$93
$3483
-
$161272
-.5 ( .5 )
$3867
-52.7 ( 52.7 )
$ -1159 ( 1159 )
-685 ( 685 )
-5.3 ( 5.3 )
-552 ( 552 )
$709
$82
-7 ( 7 )
$ -36.1 ( 36.1 )
$207692
global energy global industrial
23% ( 23 % )
$110
$120
$13
$ -269196 ( 269196 )
-22 ( 22 )
$26.90
-300 ( 300 )
$457
-3572 ( 3572 )
2.9% ( 2.9 % )
-387 ( 387 )
6 months
-5.9 ( 5.9 )
$6423
$70
-539 ( 539 )
$23.60
$1369607
-403 ( 403 )
-868 ( 868 )
-195 ( 195 )
$145.84
-7 ( 7 )
-19 ( 19 )
1.0% ( 1.0 % )
$69.35
$610.70
$ -61 ( 61 )
$8579
-19.9 ( 19.9 )
-3332 ( 3332 )
$2630
$2438.40
-1 ( 1 )
$735643
$80.42
$111.39
$59
$78
-47 ( 47 )
-22.9 ( 22.9 )
$19
shed
25% ( 25 % )
$4414
( in thousands )
$1.80
-2.0 ( 2.0 )
-140728 ( 140728 )
$367
$160.09
-64 ( 64 )
global industrial
-109.8 ( 109.8 )
$11.40
$868
$135.60
-14 ( 14 )
-1.0 ( 1.0 )
-1412 ( 1412 )
$12678
80.6% ( 80.6 % )
129% ( 129 % )
$7385
-23 ( 23 )
$91.06
102% ( 102 % )
30 years
$6630
$24.70
$1134
$24490
$10000
605 mw - boiling water
6% ( 6 % )
9.3% ( 9.3 % )
$ -
$169305
$2242.60
$4664
1.61% ( 1.61 % ) - 2.14% ( 2.14 % )
2018 2013 2023
1.9% ( 1.9 % )
$66977
-45.4 ( 45.4 )
-100 ( 100 )
-3393 ( 3393 )
$2975
$786
$90.11
$6144
$22469
October 14 2010
-3 ( 3 )
0.76% ( 0.76 % )
-2 ( 2 )
$635092
$2.00
$54.30
-15 ( 15 )
$37.60
-200 ( 200 )
$26
$32136
$555
$41
stock options
11.3% ( 11.3 % )
$107
-166 ( 166 )
$100
$ -93.1 ( 93.1 )
$938087
$985.00
$ -1.10 ( 1.10 )
-70 ( 70 )
$ -591 ( 591 )
-255 ( 255 )
7.5% ( 7.5 % )
lower operating expense
$158
$104.30
$50.89
$1534
-
$230.90
-2058 ( 2058 )
$195328
-6.7 ( 6.7 )
-6836 ( 6836 )
$140
$471
$4578
$ 1.8 billion
-4363 ( 4363 )
14% ( 14 % )
$20132
-224 ( 224 )
$879
$ -1.15 ( 1.15 )
$2714
$198
$1267
$9998
-14.8 ( 14.8 )
-364 ( 364 )
$165
-16 ( 16 )
$44376
$104
-4493 ( 4493 )
$19.60
$270
6.4% ( 6.4 % )
$26.51
-156 ( 156 )
$154.60
$6700
$80410000
global institutional global industrial
-526 ( 526 )
$661.30
$110.57
4.2% ( 4.2 % )
$2.07
-0.17 ( 0.17 )
1.99% ( 1.99 % ) 20143.28% ( 20143.28 % )
$37
-3 ( 3 )
$97
$51.00
6.49% ( 6.49 % )
49.3% ( 49.3 % )
-257 ( 257 )
-
$219.10
$ -345 ( 345 )
$64
-
-319 ( 319 )
$188
-182 ( 182 )
$126.20
$1825
$77.97
-1.8 ( 1.8 )
$293.33
7.7% ( 7.7 % )
-107 ( 107 )
$1651
49.4% ( 49.4 % )
$13280
-1263.3 ( 1263.3 )
-335 ( 335 )
$ -4887 ( 4887 )
$36.60
-19 ( 19 )
-1134 ( 1134 )
$11449
$2256
$51.57
$1023.20
owned
$2218.20
-29 ( 29 )
-4800 ( 4800 )
0.22% ( 0.22 % )
$431
1.3% ( 1.3 % )
$408
$7344
-
27.53% ( 27.53 % ) 201428.74% ( 201428.74 % )
$152
27.8% ( 27.8 % )
$19202
28% ( 28 % )
$0.30
August 2004
-
$14239
$612.10
-2145 ( 2145 )
$348
$2.45
$229967
$1900
$3677
$51.80
$183
$29905
$115
$100.00
$16117
-8994 ( 8994 )
$5526
$24.70
low
$3286
-28 ( 28 )
-3405 ( 3405 )
$23461
-.1 ( .1 )
1.1% ( 1.1 % )
$3444
-298 ( 298 )
4.61% ( 4.61 % )
$369
-911 ( 911 )
-1255 ( 1255 )
$1910.70
-606 ( 606 )
-660 ( 660 )
$0.10
-9 ( 9 )
$319
-7 ( 7 )
-
$ -52537 ( 52537 )
2.4% ( 2.4 % )
$44.00
n.a .
-10 ( 10 )
-88 ( 88 )
$142
-16 ( 16 )
$146
$3930
-76615 ( 76615 )
54.7% ( 54.7 % )
-
$1622
$ -1.10 ( 1.10 )
$1026
-5.5 ( 5.5 )
$594662
$53666
-1572 ( 1572 )
$116
-34 ( 34 )
$86
-5 ( 5 )
-53 ( 53 )
-17.6 ( 17.6 )
$3002931
$763036
-2.7 ( 2.7 )
$100
-27 ( 27 )
-122 ( 122 )
$6.30
$1800.20
-2587 ( 2587 )
-34.5 ( 34.5 )
$100
-
discovery history
$18289.00
$31347
$2160
$110.58
$2013
-16 ( 16 )
$15415
$427355
$459
$435.30
-
$23592
1.01% ( 1.01 % )
$74
$2014
$1362.20
$186
$2.39
$571
$1287
$100.00
$58
-1 ( 1 )
$149.40
$91
$140
27% ( 27 % )
14.3% ( 14.3 % )
$2940
wind
-359.4 ( 359.4 )
$176
-
$19924
$ -
$9018
3.5% ( 3.5 % )
$5642
$31.39
-3000 ( 3000 )
-996973 ( 996973 )
$59

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$284
$105
$467298
$1976987
4.60 years
$34.50
$20
$1383346
$149
$136.26
-227 ( 227 )
$2921
$165.88
-23 ( 23 )
4.84% ( 4.84 % )
1.71% ( 1.71 % )
$2590.80
$154.94
$50856
$2641
-89 ( 89 )
$21
$132
$47
discovery famillia ( u.s. )
$136597
$147.60
79% ( 79 % )
-2.4 ( 2.4 )
-6.6 ( 6.6 )
-
-14435 ( 14435 )
$70.10
-1482.8 ( 1482.8 )
-
$245692
17% ( 17 % )
$228.09
$156.70
$11695
$3462372
oswego ny
$31.16
$19
6.4% ( 6.4 % )
$128.90
$2.31
$0.41
$12657
28.6% ( 28.6 % )
29.6% ( 29.6 % )
-4368874 ( 4368874 )
-654 ( 654 )
1028 mw - pressurized water
$ 2.5 billion
$18.93
$103.88
-3 ( 3 )
$79.59
$2014
$145
$3435
$150000
-
$194
$108.50
$58370
$129.05
$5932
$1095.90
$3136.60
$165.35
$ -
28% ( 28 % )
$2.77
$209
-8475 ( 8475 )
$18.20
$ -49.61 ( 49.61 )
$299
-364 ( 364 )
$8846
$404.70
$8074
$1818
64.8% ( 64.8 % )
July 1999
$189596
$21.10
-74 ( 74 )
$1245
2.8 years
-11 ( 11 )
2032 ( a )
$100
$100.00
$3280
-10.0 ( 10.0 )
$459188
-24.8 ( 24.8 )
$100
$2081
-107 ( 107 )
-38597 ( 38597 )
-30 ( 30 )
18.1% ( 18.1 % )
$199
-
$ -80.9 ( 80.9 )
-273 ( 273 )
$156
27% ( 27 % )
-
$598.40
$125668
-6 ( 6 )
$100.00
$0.46
$11982
-12.2 ( 12.2 )
-
$12297
-3.2 ( 3.2 )
-14 ( 14 )
-7245 ( 7245 )
-363 ( 363 )
$150
tomahawk wi
$1452
$23.10
-15.6 ( 15.6 )
$15
-6.1 ( 6.1 )
-961.2 ( 961.2 )
$13920
-0.4 ( 0.4 )
$85207
$2.05
6.7% ( 6.7 % )
$79.61
$500
5.0% ( 5.0 % )
26.06% ( 26.06 % )
113% ( 113 % )
-1289 ( 1289 )
-316839 ( 316839 )
$100.00
$512
$183032
-157 ( 157 )
-34 ( 34 )
$2169720
$212.90
$26363
$5666
$35450
-0.4 ( 0.4 )
$2014
-1102 ( 1102 )
24% ( 24 % )
$12691
$508
11.4% ( 11.4 % )
$79.10
$45428
high
$90893
$158.10
$242
23.6% ( 23.6 % )
$13750
$1900
$1389
$290
$1084934
-2.0 ( 2.0 )
$180
$1482
-3 ( 3 )
-140 ( 140 )
$207.65
-4.2 ( 4.2 )
4.0% ( 4.0 % )
$ -96.1 ( 96.1 )
-5 ( 5 )
$416.52
$3331
12.9% ( 12.9 % )
$ -
$161
$476
$448.31
$167.60
$108
$102.45
129% ( 129 % )
-28 ( 28 )
$0
0.8% ( 0.8 % )
$4101370
$15421
$324.10
8.00% ( 8.00 % )
$2163.00
$150.40
-474 ( 474 )
-40.7 ( 40.7 )
8.0% ( 8.0 % )
$175.10
$104.30
$137.83
$32
-62 ( 62 )
November 2003
1.99% ( 1.99 % ) - 3.28% ( 3.28 % )
$29
-24344 ( 24344 )
$16597
$7834
$10.50
$ -
various
owned
oswego ny
$28.50
2.1% ( 2.1 % )
$10086
-36 ( 36 )
55.0% ( 55.0 % )
-126.3 ( 126.3 )
$8.25
$195276
$419
Nov . 2000
$118
-10 ( 10 )
$866.40
$971
$203.07
$4894
-182 ( 182 )
-4 ( 4 )
-32784 ( 32784 )
$5951
-3 ( 3 )
14.0% ( 14.0 % )
$29
none
September 10 2014
-.6 ( .6 )
$84.90
$72471
$123.45
-11.2 ( 11.2 )
$7680
$5642
$3730
168% ( 168 % )
$118976
-2219 ( 2219 )
-
$118
$6271
17.2% ( 17.2 % )
$1739.50
-69 ( 69 )
$160500
-94 ( 94 )
-16 ( 16 )
$1688
-103 ( 103 )
$5320
$302341
$115.79
$4835
$100
$3455
28.3% ( 28.3 % )
-9.0 ( 9.0 )
49% ( 49 % )
$558368
$6144
$111.89
$2278190
-106 ( 106 )
-1630 ( 1630 )
$5000
$273.50
$4070
$100.00
$5430
-8882 ( 8882 )
-5543 ( 5543 )
$34.80
buchanan ny
$71
-35.7 ( 35.7 )
$1200.00
-669 ( 669 )
$ -91.3 ( 91.3 )
$207
-1632 ( 1632 )
$216
$118.05
$18
1.41% ( 1.41 % )
-10 ( 10 )
$14134
$600
-
$19667
$13555
$12.14
$78.38
-232 ( 232 )
-23342 ( 23342 )
$7862
$55.08
$4625
-11186 ( 11186 )
$12953
-4 ( 4 )
owned
owned
-$0.30
$2013
-1 ( 1 )
-2 ( 2 )
$1735.50

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$2106
$3257
3.72% ( 3.72 % )
-9 ( 9 )
-33 ( 33 )
89% ( 89 % )
$53.93
112 % ( % )
is0-ne
$104.91
$2216
$461
-7 ( 7 )
$7690
$ -0.07 ( 0.07 )
-1 ( 1 )
$8167
$3.79
2.1% ( 2.1 % )
$22.95
$16285.10
8.25% ( 8.25 % )
$111
-7.4 ( 7.4 )
$187
$595338
-0.4 ( 0.4 )
-10126 ( 10126 )
$202
$659
26% ( 26 % )
-45917 ( 45917 )
$914
$1354
12.7% ( 12.7 % )
$166
2027 ( 3 )
18.41% ( 18.41 % ) - 19.45% ( 19.45 % )
-162153 ( 162153 )
11.4% ( 11.4 % )
$27.60
$42112
158.8% ( 158.8 % )
.73% ( .73 % )
$1356
$4590
102% ( 102 % )
-3.9 ( 3.9 )
-371183 ( 371183 )
$4630
$122.75
$10222
$108256
August 15 2035
$1766.70
$0.80
$982.90
$11.30
$ -1.40 ( 1.40 )
$365.63
$25.10
-2621 ( 2621 )
-23 ( 23 )
$2673
$20049
$22110
$2014
-
$103369
-414 ( 414 )
leased
-7 ( 7 )
$22008
$0.30
$108.98
-2 ( 2 )
$281.55
-406 ( 406 )
$100
11.3% ( 11.3 % )
$ -1351.4 ( 1351.4 )
-45 ( 45 )
-79.9 ( 79.9 )
$0.38
-152644 ( 152644 )
$20132
$51011
19.7% ( 19.7 % )
$3170
-76 ( 76 )
-14247 ( 14247 )
26.0% ( 26.0 % )
$6810
5.02% ( 5.02 % )
$13.10
-513 ( 513 )
$5510
$51.51
$10.26
$99264
$279
$8147
$7777
$48.07
27.43% ( 27.43 % )
$18161
$71.34
$ -5.84 ( 5.84 )
$15
$185.04
$620125
35.0% ( 35.0 % )
-11257 ( 11257 )
$323
-1076.7 ( 1076.7 )
lower gross margin from ccg platform revenue2
-5.2 ( 5.2 )
$ -139.6 ( 139.6 )
$82.12
$567048
-267 ( 267 )
$96
$33.69
$316
$338
-
$427738
$600000
$100
hydro
-35 ( 35 )
$877
--
-781 ( 781 )
-1.9 ( 1.9 )
-
-263.9 ( 263.9 )
$7874
-171.6 ( 171.6 )
$9
$15270
$324.80
$ -20.2 ( 20.2 )
$1000
$848.80
-6.8 ( 6.8 )
$10930
$418.67
$43
$100
$124
$26.25
29% ( 29 % )
$1.82
-3 ( 3 )
-
$13128
$433
$1131
$22.50
-5 ( 5 )
$0.22
$77
$6989
March 16 2017
-31781 ( 31781 )
-862.5 ( 862.5 )
$216.60
$86
-4 ( 4 )
-1001964 ( 1001964 )
$9.24
25% ( 25 % )
$149.69
-1077 ( 1077 )
-9 ( 9 )
$144
$942
$5231
$1015
-199 ( 199 )
third quarter
-44 ( 44 )
$0.55
$63.90
14.1% ( 14.1 % )
$4469
-328 ( 328 )
$37415
$180.38
$441.90
$130.80
$ -272 ( 272 )
-390 ( 390 )
$ -24 ( 24 )
-16.2 ( 16.2 )
$324
-224.5 ( 224.5 )
$400.40
( 2.0% ( 2.0 % ) )
$39
$124
$33039
-914 ( 914 )
$113.16
$59.36
-75 ( 75 )
-527 ( 527 )
$1868.70
0.0% ( 0.0 % )
$96838
$ 457 million
$ -10556 ( 10556 )
$589
$433.00
$19215
$48.10
$102
$1531000000
$34.19
$168.16
$16201
$619
$18601
indefinite
-16 ( 16 )
$5241
$1441
$16152
-84931553 ( 84931553 )
$272
$26643
$3514
12.21% ( 12.21 % ) 2013 13.57% ( 13.57 % )
-8 ( 8 )
-8322 ( 8322 )
-133.9 ( 133.9 )
-248 ( 248 )
$1208860
$3.82
$187072
$ -48.4 ( 48.4 )
$67.60
-1889 ( 1889 )
-0.3 ( 0.3 )
-35 ( 35 )
cash
$43.46
$565.10
-2047 ( 2047 )
$4727
$7536
-12.0 ( 12.0 )
$4033
2.48% ( 2.48 % )
-7.2 ( 7.2 )
$12
$103.84
$543437
$ -27 ( 27 )
$1061
$150.10
$2
$154
-52 ( 52 )
-16.4 ( 16.4 )
$3361225
$198
3.75% ( 3.75 % )
low
-84 ( 84 )
$ -150 ( 150 )
7.4% ( 7.4 % )
-100.7 ( 100.7 )
$100.00
$168.16
$ -1077 ( 1077 )
$68367
-339601 ( 339601 )
-% ( - % )
$2381
-16580 ( 16580 )
$3033
$100.00
-24.1 ( 24.1 )
$105
2.5% ( 2.5 % )
$100
-6 ( 6 )
-36 ( 36 )
wind
-36820 ( 36820 )
-1 ( 1 )
$781
1.78% ( 1.78 % )
35.6% ( 35.6 % )
$12798
$920.40
$3848
$12.39
$40.20
-1 ( 1 )
-
$6410
2.20%-2.40% ( 2.20%-2.40 % ) above 3-month libor
70% ( 70 % )
-3 ( 3 )
$100
$9896
April 14 2011
$297
-103660 ( 103660 )
$307
15.90% ( 15.90 % )
$220
129% ( 129 % )
-11144 ( 11144 )
-1558 ( 1558 )
-1.5 ( 1.5 )
-35 ( 35 )
-9516 ( 9516 )
4.0% ( 4.0 % )
$1291
6 months
$100.00
-5498 ( 5498 )
$98
amount
-116 ( 116 )
-21 ( 21 )
$177
-2.5 ( 2.5 )
-33891 ( 33891 )
$1.30
-284 ( 284 )
-535 ( 535 )
-5 ( 5 )
7.8% ( 7.8 % )
$33674
$45.86
$133.81
$ -
-23 ( 23 )
-4.5 ( 4.5 )
35.0% ( 35.0 % )
-13 ( 13 )
$38.10
$5342
$ -26.3 ( 26.3 )
$357050
$18.65
$119.43
-1349 ( 1349 )
$274
$1994
$289.34
12.5% ( 12.5 % )
-49 ( 49 )
-21.1 ( 21.1 )
$272.90
corporate headquarters and executive sales research and development offices
$146.54
-4415 ( 4415 )
$214.80
-8346 ( 8346 )

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$14419
$2.50
$267
27.85% ( 27.85 % ) - 28.51% ( 28.51 % )
$2623
-
low
$50079
$1045
$17227
-19.3 ( 19.3 )
$21056
$12201
$1802
-108 ( 108 )
$98
$1944
$2.72
$407
3.25%-3.65% ( 3.25%-3.65 % ) above 3-month libor
$147
Nov . 2012
-2693 ( 2693 )
$4.70
$359
$5943
1.6% ( 1.6 % )
$190
$2750.10
$122
-2 ( 2 )
-
-880.8 ( 880.8 )
$10983
$ -1201666 ( 1201666 )
$200
-34630 ( 34630 )
$10601
$98966
$55.94
-35 ( 35 )
-161.9 ( 161.9 )
years 3
-178.8 ( 178.8 )
$177.20
$172
-360 ( 360 )
$16
-4.2 ( 4.2 )
1.53% ( 1.53 % )
$1305
$78.25
$17188
$ -98512 ( 98512 )
27% ( 27 % )
$638.56
-96625 ( 96625 )
$7928
$348
-26 ( 26 )
-3 ( 3 )
-52 ( 52 )
4.00% ( 4.00 % )
$19864
$32619
$145.60
-970 ( 970 )
$ -25 ( 25 )
$15376
-766.6 ( 766.6 )
$75.30
-52 ( 52 )
-2093 ( 2093 )
$486.90
$14.50
$349
$1.38
386% ( 386 % )
$10
4 years
$ -19.2 ( 19.2 )
$0.38
-2359 ( 2359 )
$29616
$137
-21 ( 21 )
$18.47
-266 ( 266 )
-43.9 ( 43.9 )
-0.01 ( 0.01 )
$268496
-3.4 ( 3.4 )
1.00% ( 1.00 % )
$50.76
-1169 ( 1169 )
$139.23
$3.81
low
3.1% ( 3.1 % )
$96.90
-33 ( 33 )
$24837
$214001430
-28378 ( 28378 )
$27000
$ -1280 ( 1280 )
$175251
$125.20
3.3% ( 3.3 % )
$66
-303 ( 303 )
-826.3 ( 826.3 )
$217
18.4% ( 18.4 % )
$1151
$481273
-315.0 ( 315.0 )
$13707
-8 ( 8 )
$55.20
-11233 ( 11233 )
-99.9 ( 99.9 )
$82653000
$300000
$100.00
$214.50
-126764 ( 126764 )
2.50% ( 2.50 % )
china
10.8% ( 10.8 % )
-34 ( 34 )
$55
$130.24
-8.0 ( 8.0 )
$180.67
-357.6 ( 357.6 )
$418
$4
-16108 ( 16108 )
-26600 ( 26600 )
-11.0 ( 11.0 )
france
$122.16
$110.39
$3458
$39892
-162.6 ( 162.6 )
$51.74
100% ( 100 % )
20.0% ( 20.0 % )
$5461
( 100.0 ) % ( % )
$2014
3.8% ( 3.8 % )
global energy
-228 ( 228 )
$ -
-109823 ( 109823 )
$2937
$ -0.04 ( 0.04 )
-71 ( 71 )
-
$550.80
$1818841
$4065
$192
$ 2.7 billion
-3298 ( 3298 )
$100
-
$31300
-370.6 ( 370.6 )
( 14.1 ) % ( % )
$47
$448.60
-4 ( 4 )
4% ( 4 % )
-109 ( 109 )
$38.90
86.6% ( 86.6 % )
-17 ( 17 )
$3.89
hydro
$1225
$298378
$63884
$100
$1157
$76.79
$485.10
$2790.00
$574
$132
$975
-2.5 ( 2.5 )
$100
42.5% ( 42.5 % )
-1137 ( 1137 )
August 25 2014
$1511
0.65% ( 0.65 % ) - 1.57% ( 1.57 % )
$4848
( 2 ) % ( % )
$2564
-732 ( 732 )
$217.35
$165.50
$ -75 ( 75 )
$2577
-28 ( 28 )
4.48% ( 4.48 % )
$100
23% ( 23 % )
$125111
8.0% ( 8.0 % )
$1151
-10699 ( 10699 )
-63 ( 63 )
$21
$3204
14.2% ( 14.2 % )
-14.2 ( 14.2 )
-4969 ( 4969 )
$107
$3324
-154 ( 154 )
$200
-102 ( 102 )
$22
-1.7 ( 1.7 )
$1589
$ -0.03 ( 0.03 )
-
-24 ( 24 )
-8 ( 8 )
$976
-
filer city mi
$185.90
*
$1370
$4695
$207.32
1.0% ( 1.0 % )
$37176
$216
46% ( 46 % )
$118
2014 2013 2019
-285 ( 285 )
owned
$ -14 ( 14 )
-4 ( 4 )
-59.4 ( 59.4 )
-22.8 ( 22.8 )
$191
70% ( 70 % )
-46.3 ( 46.3 )
$ -31 ( 31 )
$79
-165211 ( 165211 )
$38760
amount ( in millions )
19% ( 19 % )
5% ( 5 % )
7% ( 7 % )
$34504
$126488
$0.40
$ -7199 ( 7199 )
$21
$40273
$186
-11 ( 11 )
-212 ( 212 )
-281 ( 281 )
12.9% ( 12.9 % )
$6708
$290
-
$120.40
-116 ( 116 )
$2758
vernon vt
$6373
22.1% ( 22.1 % )
$36.06
$2800
$1791.80
37.02% ( 37.02 % )
$3365
3.1% ( 3.1 % )
$270
19.03% ( 19.03 % )
-
discovery en espanol ( u.s. )
$44.10
$7157
$241
14.3% ( 14.3 % )
$155.17
$100
high
-25 ( 25 )
-1164 ( 1164 )
-4123 ( 4123 )
$56.53
$26677
-3196 ( 3196 )
-346.6 ( 346.6 )
$ -2.05 ( 2.05 )
$119.89
February 2004
$118.43
29.10% ( 29.10 % )
-
-65 ( 65 )
-7.7 ( 7.7 )
$69.80
$ -1004 ( 1004 )
6% ( 6 % )
$6000
-344 ( 344 )
$2997
$217969
3.4% ( 3.4 % )
$143
-4 ( 4 )
$254
$7256
12.07% ( 12.07 % )
$852
$5167643
$318063
-9091 ( 9091 )
-72.4 ( 72.4 )
( 11.4 ) % ( % )
$286424
$ -331 ( 331 )
$36.53
leased
$86
-4.6 ( 4.6 )
$7970
$8
35% ( 35 % )
$161.39
*
-150 ( 150 )
$343
$136597
$281.24
-240 ( 240 )
$105
$42.61
-1.3 ( 1.3 )
$ 232 million
-443 ( 443 )
$1250
23% ( 23 % )
$67.70
$1252
-
$13509
( in thousands )
$832
$113.61
$10
$34366
$915
$150
$1355
$21808
-50865 ( 50865 )
$79
$32619

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$47
$162.53
$4217
8.0% ( 8.0 % )
$35.00
-
$150.50
-506 ( 506 )
$942
-
$100.00
11.8% ( 11.8 % )
$6238
$59.84
$1266
$99
$357
9% ( 9 % )
$ -27 ( 27 )
-19 ( 19 )
-3 ( 3 )
( 0.8% ( 0.8 % ) )
$135.35
-169.9 ( 169.9 )
$229134
$7384
$100.00
$1683
$872.70
$279
$86103
-863 ( 863 )
$227
$19.28
$781118739
$1.62
$771
nan
$189.72
$53.80
3.2% ( 3.2 % )
$ -0.57 ( 0.57 )
$3234
-3 ( 3 )
$107
$75.93
$ -8 ( 8 )
$23
$173
$267.70
$71.08
$20704
$6612
$314
-109 ( 109 )
$6305
$6823
$ -4901 ( 4901 )
$ -
$5598
83.7% ( 83.7 % )
$1511
$853493
$93.00
wind
$283
$139.75
$2131
$5.73
$241577
$6575
$45
$1053
$713202
$3760
100% ( 100 % )
-3.7 ( 3.7 )
35.31% ( 35.31 % ) - 36.63% ( 36.63 % )
$777
$2014
$1422426
$968
high
-187 ( 187 )
$11365
-27 ( 27 )
$13373
$2.33
$7.20
-9.6 ( 9.6 )
$22
$206
-5.7 ( 5.7 )
7.12% ( 7.12 % )
$147.87
$22642
6 months
-116 ( 116 )
3.24% ( 3.24 % )
-
$666
2.10% ( 2.10 % ) above 3-month libor
-995 ( 995 )
$151.43
$49
$3403
-47 ( 47 )
$1637
$ -531 ( 531 )
$15750
$1762150
$ -1.93 ( 1.93 )
$294269
-7.9 ( 7.9 )
5.52% ( 5.52 % )
$751
$18.84
$1509.70
-149 ( 149 )
1.5% ( 1.5 % )
$98387
-4849 ( 4849 )
-752 ( 752 )
$25955
$ -8387 ( 8387 )
-2 ( 2 )
-
-6 ( 6 )
$298
26 - 29% ( 29 % )
$1923
$255
$2014
19 % ( % )
6 months
-2083 ( 2083 )
4.7% ( 4.7 % )
$213.14
$11199
$505
1.64% ( 1.64 % )
$ -5 ( 5 )
-24 ( 24 )
$19315
$ -186724 ( 186724 )
25% ( 25 % )
$319
$14607
$ -720 ( 720 )
$51.27
-8.1 ( 8.1 )
$317742
$ -3754 ( 3754 )
$222.09
0.06% ( 0.06 % ) 2013 0.11% ( 0.11 % )
-50 ( 50 )
$6150
$24006
-50 ( 50 )
( 1.8% ( 1.8 % ) )
$93500
56.9% ( 56.9 % )
$8093
$2510
--
-3468 ( 3468 )
-8.0 ( 8.0 )
$104.10
$451000000
1.2% ( 1.2 % )
-
-61301 ( 61301 )
1.44% ( 1.44 % )
12.61% ( 12.61 % )
$100.00
$50.50
58.7% ( 58.7 % )
$20740
$9
$134935
17.6% ( 17.6 % )
$97.04
-297 ( 297 )
$800
-47 ( 47 )
( in thousands )
$113.69
$5222
-1857 ( 1857 )
$559973
$3360499
$600.30
-42.2 ( 42.2 )
$1859
$825.00
-17 ( 17 )
-2 ( 2 )
$1338
( 1.5% ( 1.5 % ) )
-11 ( 11 )
$9.70
-5 ( 5 )
$22.72
-49528 ( 49528 )
$4190
2015 ( c )
-3 ( 3 )
$158489
$15570
$132
-3.3 ( 3.3 )
$2014
$639
$ -335360 ( 335360 )
$18.89
brazil
$345.60
$100
$370466
-24 ( 24 )
-23.1 ( 23.1 )
-8 ( 8 )
$100
$4455
$130206
-17.1 ( 17.1 )
$669.50
-4.3 ( 4.3 )
$247
$ -188 ( 188 )
$2420.90
$3743
4.4% ( 4.4 % )
$23.30
$338421933
-7449 ( 7449 )
-188 ( 188 )
-
9.8% ( 9.8 % )
$2130
$8154
-24 ( 24 )
$5.65
-3 ( 3 )
-4 ( 4 )
-1649.1 ( 1649.1 )
$2014
$ -9457 ( 9457 )
20% ( 20 % )
$217
$133624
$1375
-6469 ( 6469 )
$30.51
years
leased
-663 ( 663 )
$17118
low
$5.30
-154 ( 154 )
-376 ( 376 )
$40
$76.96
49% ( 49 % )
$4120030
2014% ( 2014 % )
-980 ( 980 )
$11143
$76
$11.70
April 1 2022
5% ( 5 % )
$5425
$89
united states
china
$100.00
-
2012 2013 2014
$1762
$2052
$53.56
-17 ( 17 )
-291.7 ( 291.7 )
$479
$25782
$512.20
-
$653
-
$20.60
$2160.20
$7579
*
$3768
1.35% ( 1.35 % )
-15685 ( 15685 )
-31.2 ( 31.2 )
( 21 ) % ( % )
$6273
$1100
$83
$42
$178
$222.44
-38 ( 38 )
33.3% ( 33.3 % )
$338.50
$21384
6.1% ( 6.1 % )
$171
$6215
$7027
$173
$10110
-3232 ( 3232 )
-1791 ( 1791 )
-3 ( 3 )
$ 416 million
$1887
$892033
owned
-
$ -24.4 ( 24.4 )
$0.90
class c ( series i )
$29822
$13670
$4045
$3896
owned
-1279049 ( 1279049 )
-
$9371
$2014
-163 ( 163 )
-195 ( 195 )
$8940

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

28% ( 28 % )
dmax ( b )
$ -114 ( 114 )
$1327974
-67.7 ( 67.7 )
$34
$17.30
-47.1 ( 47.1 )
-0.6 ( 0.6 )
$619
$338421933
$2014
30.9% ( 30.9 % )
-0.1 ( 0.1 )
-1879 ( 1879 )
22% ( 22 % )
$756703
$22.85
$138
-
-17.8 ( 17.8 )
$607
-
$145.60
$651779
-21 ( 21 )
$41
$138
100% ( 100 % )
$659
2.8% ( 2.8 % )
-4 ( 4 )
-1526 ( 1526 )
4.45% ( 4.45 % )
$10.26
--
$2257
$395155
-250.4 ( 250.4 )
$46.40
$4241
-805 ( 805 )
$2559
$ -8564 ( 8564 )
$215
$7722
-207 ( 207 )
-1060 ( 1060 )
3% ( 3 % )
$740507
$77622
-7199 ( 7199 )
117% ( 117 % )
-10 ( 10 )
scotland
-309 ( 309 )
$112.80
$132.40
$223.79
5.7% ( 5.7 % )
-3 ( 3 )
29% ( 29 % )
$4425
$10406
$102.11
$ -517 ( 517 )
$3056
3.5% ( 3.5 % )
$100.00
$ -249 ( 249 )
$1008.70
-91 ( 91 )
$114251
$6091
$51
$10.60
$1524
$77089
0.05% ( 0.05 % ) 2013 0.12% ( 0.12 % )
$13.54
-124.6 ( 124.6 )
$651.50
-46.9 ( 46.9 )
-17.4 ( 17.4 )
$66.09
$543
8.4% ( 8.4 % )
$176.94
-2.3 ( 2.3 )
$48407
$192.20
$2320
$318477
-6234 ( 6234 )
$154.60
-6 ( 6 )
$967
-942 ( 942 )
-1 ( 1 )
$2.54
$188
1.0% ( 1.0 % )
29.60% ( 29.60 % )
-58.8 ( 58.8 )
$170.45
$ -
$28520
$8013
-98 ( 98 )
$190.66
$22883
$2700
$33.90
-21 ( 21 )
$793
$3531.40
11.9% ( 11.9 % )
$243.73
53.5% ( 53.5 % )
22.90% ( 22.90 % )
$73501
$65.53
-130 ( 130 )
$1736.80
-638 ( 638 )
$1072
-10301 ( 10301 )
$0.38
$115.99
3.573% ( 3.573 % )
$408424
-9 ( 9 )
$3767061887
$ -9 ( 9 )
$13.12
$ -77 ( 77 )
$21885
$34
$3361
$100.00
$148.90
$157.22
$22.97
3.1% ( 3.1 % )
20.43% ( 20.43 % ) - 21.85% ( 21.85 % )
$65225
$151962
-81 ( 81 )
-17 ( 17 )
1.58% ( 1.58 % )
$58.02
$558.80
$2014
$1513.80
$93.38
-31608 ( 31608 )
$79789
$311
$53.61
$4681
$102.40
-386.9 ( 386.9 )
$126.30
$204866
-43.6 ( 43.6 )
$1079
$70.30
-56 ( 56 )
119% ( 119 % )
$444
-2488 ( 2488 )
$350000
$84751
$466.10
million
$7132
$263214
$2788162
$27941
$25.10
$11
-9733 ( 9733 )
22% ( 22 % )
-
-4369 ( 4369 )
-
0.09% ( 0.09 % )
$25544
leased
$84
-4 ( 4 )
-105.6 ( 105.6 )
-10587 ( 10587 )
1.4% ( 1.4 % )
$10258
-370 ( 370 )
$137
3.1% ( 3.1 % )
$3.85
$2997
$37529
-
$198.09
$128.43
$115.06
$49
-7 ( 7 )
$1542
$24569
-28 ( 28 )
26% ( 26 % ) - 29% ( 29 % )
-148011884 ( 148011884 )
-154 ( 154 )
$163
December 2003
$0.42
-10 ( 10 )
$14084
-61871 ( 61871 )
$294741
-10.4 ( 10.4 )
4.0% ( 4.0 % )
$8246
-6327 ( 6327 )
$2632.50
1.3% ( 1.3 % )
26% ( 26 % )
$58.00
$7426
2.31% ( 2.31 % )
-700 ( 700 )
-102.8 ( 102.8 )
-60.4 ( 60.4 )
$62.12
$80.74
$2311
-1754 ( 1754 )
-97 ( 97 )
$33.20
$ -8595 ( 8595 )
$1466
$222088
$1807885
$212.19
-656 ( 656 )
-21 ( 21 )
-31082 ( 31082 )
$481
-12023.4 ( 12023.4 )
-261 ( 261 )
-.5 ( .5 )
-17 ( 17 )
$151.90
$691
$200
$284
$744
$ -27 ( 27 )
$17745
$1927
$1503
-531 ( 531 )
-113.1 ( 113.1 )
$17274
$189
-$75
-
28.22% ( 28.22 % )
35.26% ( 35.26 % ) - 35.27% ( 35.27 % )
$233.56
$14243
$2390
business continuity and co-location
$2266
$617400
-
$1125
$100
none
$128
$499
-51206 ( 51206 )
$ -16550 ( 16550 )
-
50% ( 50 % )
-5 ( 5 )
$745.70
2014% ( 2014 % )
-510590 ( 510590 )
5% ( 5 % )
$175284073
-22234 ( 22234 )
( 2 ) % ( % )
$10592
-
-0.4 ( 0.4 )
$37899
$4694
32% ( 32 % )
-202 ( 202 )
$510
$102
$36
$24673
-6373 ( 6373 )
$568649
$80.70
$860299
-2.0 ( 2.0 )
$55.04
$153
$145.49
$479
-380 ( 380 )
-46 ( 46 )
$26269
$157
$6836
$44.20
$301.20
$21.37
$2
$2
$215
$84.90
$117.11
$252030
$3016
$1313
$11.00
-53.2 ( 53.2 )
$3277
$150.49
-40 ( 40 )
$ -42 ( 42 )
$ -70.1 ( 70.1 )
24.11% ( 24.11 % )
--
40% ( 40 % )
-
$61.36
$182947
-7802 ( 7802 )
$ -39 ( 39 )
$688.50
$158996
*
$1735.90
-0.4 ( 0.4 )
$5834
$13632
$365251
$146865
$263702132
-34908 ( 34908 )
$1
$1272
31.29% ( 31.29 % )
$27
44.6% ( 44.6 % )
$1624
100% ( 100 % )
$153
-198 ( 198 )
-607 ( 607 )
$195
$294
nyiso
lower factory start-up costs primarily driven by the ramp of our 14nm process technology
-3365 ( 3365 )
$43.64
$63.87
-200 ( 200 )
$213
-16.6 ( 16.6 )
$1242
$580
$1679.70
$102.53
-1102 ( 1102 )
$190
( 3 ) % ( % )
-882 ( 882 )
$1.58
$ -19 ( 19 )
-
$14.20
-17.2 ( 17.2 )
-5 ( 5 )
26% ( 26 % )
$288.40
$92.42
$4595
$0.42
-10 ( 10 )
( in thousands )
-103 ( 103 )
leased
1.9% ( 1.9 % )
$62.09
11% ( 11 % )
$14.90
14% ( 14 % )
-1.1 ( 1.1 )
$9.89
owned
-2.4 ( 2.4 )
$100.00
$173.33
-30.1 ( 30.1 )
$1570
$68.10
27.3% ( 27.3 % )
$116
$42.81
$156508
$2590
$7.80
40% ( 40 % )
$89.49
$1.14
$221.70
$65.10
-30.7 ( 30.7 )
-348 ( 348 )
1.2% ( 1.2 % )
$100
$2499
15.3% ( 15.3 % )
$16
$118.80
$73
-
35% ( 35 % )
$ -19011 ( 19011 )
$55178
$158.20
27.85% ( 27.85 % ) 201428.51% ( 201428.51 % )
$350000
$366150
$5.60
$4525
$100
$1999
$296.67
$3174
$159819370
18.9% ( 18.9 % )
16% ( 16 % )
25% ( 25 % )
$5400
$21871
$197.70
123% ( 123 % )
60% ( 60 % )
-1.2 ( 1.2 )
2.9% ( 2.9 % )
$1663
$129.00
$3341

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?

$3532
-
$4283493
$111
$364
$136
$208
-104 ( 104 )
$1603
$100
-
$93
$367.10
$66.91
-119 ( 119 )
( 4 ) % ( % )
-136058 ( 136058 )
-47.9 ( 47.9 )
3.2% ( 3.2 % )
$100.00
3.2% ( 3.2 % )
-21081 ( 21081 )
$248251
17% ( 17 % )
2.9% ( 2.9 % )
$6292
$212
$4214.50
-4.4 ( 4.4 )
123% ( 123 % )
$1265
3.95% ( 3.95 % )
amount
$657
$140160
$14953
$328275
$21579
$94.20
$14
-
51% ( 51 % )
$5940
owned
-64830 ( 64830 )
$35.30
$5829
-1456 ( 1456 )
-15 ( 15 )
low
$1590873
33% ( 33 % )
-31 ( 31 )
$ -245814 ( 245814 )
-817 ( 817 )
$988
$162
$87
$ -1168 ( 1168 )
-138 ( 138 )
-56 ( 56 )
$609
$ -
$278.40
$338421933
$33.81
$ -2769 ( 2769 )
$127.80
-3.8 ( 3.8 )
4.2% ( 4.2 % )
-3939 ( 3939 )
10.25% ( 10.25 % )
-489 ( 489 )
$3.80
$ -485 ( 485 )
$3979
$754.30
$1135
$10
-189 ( 189 )
-2.2 ( 2.2 )
$21.70
$27999
$ -40.9 ( 40.9 )
$2435
-3 ( 3 )
$ -0.09 ( 0.09 )
$991.10
discovery kids
$47760
2.8% ( 2.8 % )
-142 ( 142 )
-38949 ( 38949 )
$3018
$116
$148.89
$346
-10.4 ( 10.4 )
-2.0 ( 2.0 )
-84 ( 84 )
*
0.0% ( 0.0 % )
-259 ( 259 )
$4082
-3178.8 ( 3178.8 )
50% ( 50 % )
$24.57
June 30 2009
$1791.80
$100.00
$ -49.14 ( 49.14 )
-6 ( 6 )
$167470
$206.86
23% ( 23 % )
trading floor and office space
$2357
12.9% ( 12.9 % )
$ -2502 ( 2502 )
higher factory start-up costs primarily driven by the ramp of our 10nm process technology
$1.72
-1446 ( 1446 )
$2014
$143
$91.80
-
$8972
$231
$126.72
-9427 ( 9427 )
9% ( 9 % )
$ -943 ( 943 )
$38741
35% ( 35 % )
11.4% ( 11.4 % )
-54 ( 54 )
$28681
$5.94
-18391 ( 18391 )
June 10 2014
$878
$100.00
-16611 ( 16611 )
$12935
-32.5 ( 32.5 )
$78.76
.27% ( .27 % )
$447
$100
$523.80
-314242 ( 314242 )
$41
-6.3 ( 6.3 )
$244.64
$811554
$1043.70
-6 ( 6 )
$100.00
$4638
$275
$3338
3.3% ( 3.3 % )
$39.80
-
-521 ( 521 )
-5829 ( 5829 )
$1026
-2128 ( 2128 )
$632100
$245769
-
80% ( 80 % )
$887
commercial research and development manufacturing
discovery history
$143559758
$129
$495
-29.5 ( 29.5 )
2.4% ( 2.4 % )
-685 ( 685 )
$2476
$1261
$ -35 ( 35 )
-55851 ( 55851 )
$1352
$19.78
$ -369 ( 369 )
$9091
-
-28000 ( 28000 )
$627444
$1420
-23 ( 23 )
-62 ( 62 )
3.03% ( 3.03 % )
$32011
76.6% ( 76.6 % )
$138.40
$103.19
$100.00
$0
$221
-43 ( 43 )
-2175 ( 2175 )
$34.67
64.9% ( 64.9 % )
$222
$156
-148527 ( 148527 )
$100.00
10.57% ( 10.57 % )
-1255 ( 1255 )
$ -748 ( 748 )
$18.90
-.1 ( .1 )
-2247 ( 2247 )
$156.80
-269 ( 269 )
$3260
$2074
$5943
-65 ( 65 )
$186.37
$669
3.4% ( 3.4 % )
-75 ( 75 )
9% ( 9 % )
22% ( 22 % ) - 27% ( 27 % )
$250
-1 ( 1 )
-0.09 ( 0.09 )
$9.70
$ -27996 ( 27996 )
120% ( 120 % )
$1167.50
-94800 ( 94800 )
$15486
$22062
2.54% ( 2.54 % )
$11
$170.80
$119.07
4 years
-11 ( 11 )
$2014
$331
-12807 ( 12807 )
$642.60
-28853 ( 28853 )
$202.90
$105
$121.95
-1299 ( 1299 )
7.5% ( 7.5 % )
-1504 ( 1504 )
$75.95
-578 ( 578 )
-5 ( 5 )
$107.75
$2013
$1235
-3.2 ( 3.2 )
$243040
$19097
$220600
April 14 2008
$1679.70
$16960
4.23% ( 4.23 % )
-6 ( 6 )
-9 ( 9 )
$2.31
$ -3929 ( 3929 )
$134
-187 ( 187 )
$54.10
$20.01
$53
$3.85
$306
$602011
-40 ( 40 )
.04% ( .04 % )
$100
$3.75
$2.96
$100.00
$28887
$13.01
$106.36
5.00% ( 5.00 % )
$323606
-148.2 ( 148.2 )
$107.87
$727.60
$165
$18
-9.5 ( 9.5 )
-964740 ( 964740 )
-
$22.10
-1 ( 1 )
-3.0 ( 3.0 )
$100
3.6% ( 3.6 % )
$ -2680 ( 2680 )
-79 ( 79 )
( 163 ) ( b )
$86.20
605 mw - boiling water
-511 ( 511 )
$73200
$0.46
$639
$ 226 million
$2500
$3825
-8 ( 8 )
$132
$118180
14.93% ( 14.93 % )
$ -6731 ( 6731 )
9.1% ( 9.1 % )
$73.20
$1636526
$151
-.6 ( .6 )
-2 ( 2 )
4.60% ( 4.60 % )
$337.60
18% ( 18 % )
-2 ( 2 )
owned
$57761
$1972
$183032
-1229 ( 1229 )
$14415
$ -3273 ( 3273 )
$556400
$ -1180005 ( 1180005 )
$1290
135% ( 135 % )
-10 ( 10 )
$1230000
51% ( 51 % )
$41.70
-79 ( 79 )
$23788
-
-104187 ( 104187 )
-135.4 ( 135.4 )
11.1% ( 11.1 % )
$593
$20086
5.04% ( 5.04 % )
-2225 ( 2225 )
-17.1 ( 17.1 )
$78.40
-18 ( 18 )
$13.75
$1623.90
$6205
$243.00
discovery familia ( u.s. )
$0.10
$2166
7.50% ( 7.50 % )
$813
$23788
$157
$166536
$1916
-633 ( 633 )
$102.53
$389.20
research and development offices
11.8% ( 11.8 % )
$4
1.7% ( 1.7 % )
161.3% ( 161.3 % )
$6230
$5561
-29.6 ( 29.6 )
$10374
$228.88
$104222
-4 ( 4 )
$25684
$12416
253 ( c )
60.8% ( 60.8 % )
29% ( 29 % )
$372320
$11
$126.40
$2471
$157.94
1.3% ( 1.3 % )
$100.00
14.14% ( 14.14 % )
$200265
-16 ( 16 )
$132.23
quest
$105.80
17.7% ( 17.7 % )
-22.0 ( 22.0 )
-2354 ( 2354 )
$160.61
1.2% ( 1.2 % )
-858 ( 858 )
14% ( 14 % )
-5 ( 5 )
24% ( 24 % )
$31
2.40% ( 2.40 % )
$3297
$ -2401 ( 2401 )
-90955 ( 90955 )
$5142
$7.60
$20807
-53 ( 53 )
9.1% ( 9.1 % )
$347.40
-136 ( 136 )
-3176 ( 3176 )
$525
$4009641
$26214
1.4% ( 1.4 % )
$19259
-240 ( 240 )
$177.58
28% ( 28 % )
-18 ( 18 )
$2014
-43.0 ( 43.0 )
$10
-27 ( 27 )
1.70% ( 1.70 % )
-831 ( 831 )
-
$571.10
$2.96
41.7% ( 41.7 % )
3.634% ( 3.634 % )
$10435
$5596
$114
$1051
$776
-413 ( 413 )
$1215
$372.40
$245

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

high
-872 ( 872 )
$909
-50 ( 50 )
-10 ( 10 )
$178.22
$2013
$10509
50.3% ( 50.3 % )
-103 ( 103 )
$605
indefinite
$9169822
-9 ( 9 )
$54
$ -3550 ( 3550 )
-313 ( 313 )
$176693
$24495
$104
-31713 ( 31713 )
$164
$18916
-43 ( 43 )
-9 ( 9 )
$ -2207 ( 2207 )
$ -0.51 ( 0.51 )
$67436
-8 ( 8 )
-30 ( 30 )
$280661
$102794
$2248
$ -2.35 ( 2.35 )
-
0.7% ( 0.7 % )
30.9% ( 30.9 % )
$285.81
$296184
commercial research and development manufacturing
$1485.70
-9899 ( 9899 )
1.45% ( 1.45 % )
25% ( 25 % )
$20776
$71.59
$213
$229.59
$617
$1697.60
chile
$ -69.1 ( 69.1 )
$2197
is0-ne
$4209
$95.70
$12223
$4491
$282
$51637
-945.6 ( 945.6 )
$91.15
-23906 ( 23906 )
high
1.0% ( 1.0 % )
$21.00
-292.5 ( 292.5 )
-4.8 ( 4.8 )
$4096
-12 ( 12 )
19.0% ( 19.0 % )
-
994% ( 994 % )
16.7% ( 16.7 % )
$55
$164.20
$13429
$66.90
$15.88
( in thousands )
$1951
April 1 2018
-60 ( 60 )
-3 ( 3 )
-401699 ( 401699 )
-8 ( 8 )
$ -5761 ( 5761 )
$146.98
discovery en espanol ( u.s. )
$43438
-663 ( 663 )
25.9% ( 25.9 % )
$ -1401 ( 1401 )
$2494.30
$74896
$19686
-9 ( 9 )
-2668 ( 2668 )
$241
$93.21
$113972
$1413
48.6% ( 48.6 % )
$34.92
60% ( 60 % )
-
-247 ( 247 )
-6796 ( 6796 )
-11.3 ( 11.3 )
$115.40
$226
-903.5 ( 903.5 )
$ -5534 ( 5534 )
-$45
-88.4 ( 88.4 )
$33992
$10.20
$147.90
$98
$1.70
39.5% ( 39.5 % )
$1597
$27000
0.40% ( 0.40 % )
-864.8 ( 864.8 )
$283.00
-990 ( 990 )
$196545
-807 ( 807 )
$221
$181
-36.7 ( 36.7 )
-
$55.80
$1.16
-219 ( 219 )
$104222
$49.90
$9409
$140.50
-0.4 ( 0.4 )
$306222
-8.1 ( 8.1 )
$100.00
92.3% ( 92.3 % )
$979
-10 ( 10 )
$18
-40.6 ( 40.6 )
$83
$8
chile
-1 ( 1 )
$793000
$208
$189.41
$5920
-973 ( 973 )
class b ( 2 )
$989
$8.50
$441
$2.10
-4261 ( 4261 )
-5 ( 5 )
-35 ( 35 )
$6197
$3015
$4209.60
$58.52
$48.45
$ -13 ( 13 )
$1.26
$ -39.0 ( 39.0 )
$11
$116.64
$7491
-8701 ( 8701 )
$144.60
-250 ( 250 )
-56 ( 56 )
$6039.00
$124
-14068 ( 14068 )
$157.03
27.5% ( 27.5 % )
$60.94
-4 ( 4 )
$ -1285.8 ( 1285.8 )
$836
-0.18 ( 0.18 )
$ -6091 ( 6091 )
$2522
-7274 ( 7274 )
-18 ( 18 )
-36437 ( 36437 )
-$5
-539 ( 539 )
$53.12
$257.00
$1813
-1158 ( 1158 )
11.1% ( 11.1 % )
$1.07
$1619
$1186
$177
$106.73
$0
$139.55
$ -111 ( 111 )
$182.85
-502 ( 502 )
$176.30
$2014
21% ( 21 % )
-24 ( 24 )
-139 ( 139 )
-54.9 ( 54.9 )
$1575
$ -794 ( 794 )
$2014
-33 ( 33 )
$294.49
-86.3 ( 86.3 )
-360 ( 360 )
28.51% ( 28.51 % )
$68662
$3823
$51417
-2344 ( 2344 )
-24.6 ( 24.6 )
nyiso
$7540
$1120
-
50% ( 50 % )
$125700
-240 ( 240 )
-4249 ( 4249 )
-17 ( 17 )
$6147
$ -31 ( 31 )
-909 ( 909 )
$60633
-4969 ( 4969 )
$185
2.5% ( 2.5 % )
$ -
$172.10
66.3% ( 66.3 % )
$346
24% ( 24 % )
$25906
-29.7 ( 29.7 )
% ( % )
5.3% ( 5.3 % )
$ -49.4 ( 49.4 )
-52 ( 52 )
-962 ( 962 )
-1376 ( 1376 )
$51.81
-41.8 ( 41.8 )
$1380573
$40.07
-.8 ( .8 )
$29
84.5% ( 84.5 % )
50.1% ( 50.1 % )
$24622
$9381
-1830004 ( 1830004 )
-27 ( 27 )
1.30% ( 1.30 % )
-287.7 ( 287.7 )
-682.0 ( 682.0 )
$270
6% ( 6 % )
-1.3 ( 1.3 )
$287.90
$42.12
$115.61
-8 ( 8 )
-10 ( 10 )
$219
72% ( 72 % )
$15386
4.93% ( 4.93 % )
-11100 ( 11100 )
-1 ( 1 )
$280
$1562
$59.34
$ -66 ( 66 )
-54 ( 54 )
$298
6% ( 6 % )
$0
8.0% ( 8.0 % )
$5000
$2410
-
$132
$278.60
$3854
$29628
$178.02
$187
-517444 ( 517444 )
$178.46
$3262
6.1% ( 6.1 % )
-13.6 ( 13.6 )
-498 ( 498 )
-
-22 ( 22 )
-10 ( 10 )
0.75% ( 0.75 % )
$2458777
-
1.75% ( 1.75 % )
45.81% ( 45.81 % )
$1216.70
-1853 ( 1853 )
$44.48
-196.2 ( 196.2 )
-154273 ( 154273 )
-260 ( 260 )
buchanan ny
$2
( 1.1% ( 1.1 % ) )
$126098
$110.80
$3509
$859039458
$9164
$ -0.01 ( 0.01 )
$805742
-2059 ( 2059 )
$476
$242706
-190 ( 190 )
$126.90
$40327
-2.7 ( 2.7 )
$168.17
$250
$140
$199539
$673.40
$17
$250
$17.50
-3 ( 3 )
$324502
$3713
-
3.2% ( 3.2 % )
2016 ccg operating income
0.10% ( 0.10 % )
-1741 ( 1741 )
-2 ( 2 )
-46.5 ( 46.5 )
-1486 ( 1486 )
2.7% ( 2.7 % )
$2.07
$100.00
-0.2 ( 0.2 )
$24800
$393810
$1700
$144
$178
$299
$368.80
$506032
$112
$82
$242.20
1.4% ( 1.4 % )
29% ( 29 % )
$3781
8.1% ( 8.1 % )
-3267 ( 3267 )
$3625459
$42
-12 ( 12 )
$5563.70
$ -
$142.50
-30.2 ( 30.2 )
$5275
$ -
$41431
-70 ( 70 )
$118
-28.8 ( 28.8 )
$130
-16621 ( 16621 )
$40782
-3.7 ( 3.7 )
$5457
$190.81
$10782
$858543
-401 ( 401 )
$24241
-6.2 ( 6.2 )
-0.9 ( 0.9 )
$75000
$1250
$572764
$16453
$24.54
$270382
31.4% ( 31.4 % )
$0.30
$3.75
-41 ( 41 )
-155 ( 155 )
-
-459.6 ( 459.6 )
43% ( 43 % )
-2 ( 2 )
19.37% ( 19.37 % )
$132.50
-2728 ( 2728 )
30.8% ( 30.8 % )
264.3% ( 264.3 % )
$2.70
-2513 ( 2513 )
$59
$ -139 ( 139 )
-29 ( 29 )
$5321
-98092 ( 98092 )
-1412 ( 1412 )
$225679
-
$96.54
$20304
-0.4 ( 0.4 )
$121
$1215
$349.40
-44 ( 44 )
-3 ( 3 )
$0.65
$4566
-47 ( 47 )
$5191
$2152
-100 ( 100 )
$8651
-15 ( 15 )

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$66
-784 ( 784 )
56.4% ( 56.4 % )
$192
-20.3 ( 20.3 )
$155
$5548.90
$743
$2979
35.0% ( 35.0 % )
$174
$307403
-38126 ( 38126 )
-5 ( 5 )
$3625
-1 ( 1 )
-1146 ( 1146 )
$25.96
-927.8 ( 927.8 )
$ -48227 ( 48227 )
$17869
$506
-305.2 ( 305.2 )
-0.2 ( 0.2 )
-715.4 ( 715.4 )
$6178.80
$1075
$100
$26.90
$3809
8.3% ( 8.3 % )
-95 ( 95 )
$121
$51004
$22.38
$53.97
$105
4.7% ( 4.7 % )
-
-115415 ( 115415 )
$104.02
$1800
$269
$96.90
$177.40
16.7% ( 16.7 % )
$50.34
$460961
$617039
$1013.00
2.30% ( 2.30 % )
-482 ( 482 )
-989.8 ( 989.8 )
-4066 ( 4066 )
other
-1286 ( 1286 )
$311
25.82% ( 25.82 % )
$15386
$ -3.02 ( 3.02 )
-3 ( 3 )
-46.8 ( 46.8 )
$127.96
$51699
$13109
-568377 ( 568377 )
-15244 ( 15244 )
$228
$6083
( 22 ) % ( % )
$ -1269 ( 1269 )
$1154.20
-4 ( 4 )
$1854
$136.18
$5.95
owned
5.9% ( 5.9 % )
$2014
$815
-16 ( 16 )
$282
40% ( 40 % )
$258787
$3352
$8518
49.2% ( 49.2 % )
$74
3% ( 3 % )
-270 ( 270 )
-240.9 ( 240.9 )
-1419840 ( 1419840 )
-6.5 ( 6.5 )
nyiso
$100
$100.00
-16 ( 16 )
$151.89
-7 ( 7 )
$17182
40bp
$128.15
$2610
-
$3
-0.4 ( 0.4 )
9.0% ( 9.0 % )
$22560
25% ( 25 % )
$219
-
$6656.00
28.7% ( 28.7 % )
$0.40
$1329
$18.40
-182 ( 182 )
-10 ( 10 )
$ -14325 ( 14325 )
$ -14355 ( 14355 )
100% ( 100 % )
-1.5 ( 1.5 )
$415000
-1732 ( 1732 )
-35.1 ( 35.1 )
-69 ( 69 )
$18884
$400023
$7620
$558026
$331.43
-1 ( 1 )
$13
$1160677
-8 ( 8 )
0.19% ( 0.19 % )
$86
-680 ( 680 )
$267
$56.05
$94.06
vernon vt
$483578
$100.00
$78.53
$612
$7087
$ 1.7 billion
$402
$83.69
October 14 2015
-1137 ( 1137 )
$18387
$803
13.7% ( 13.7 % )
-3119 ( 3119 )
-967 ( 967 )
$25.96
$6713155
$45
$125
valdosta ga
-114 ( 114 )
$173
$20684
July 1999
-5.9 ( 5.9 )
$613
$5909
-63 ( 63 )
4.51% ( 4.51 % )
office space
$602.08
3.2% ( 3.2 % )
$104681
$12.75
$7443
$ -26.9 ( 26.9 )
5.00% ( 5.00 % )
$ 1.4 billion
-1345412 ( 1345412 )
15 years
-31250 ( 31250 )
$2860
-142423 ( 142423 )
$ -9926 ( 9926 )
-617 ( 617 )
$21135
$917
-7 ( 7 )
( 69.4 ) % ( % )
-253907 ( 253907 )
$ -
-37485 ( 37485 )
-1 ( 1 )
28.0% ( 28.0 % )
-319 ( 319 )
$108
26% ( 26 % )
$87397
$9495246
$ -4120 ( 4120 )
37.9% ( 37.9 % )
$79.84
$1701.10
-54 ( 54 )
$191
$0.46
103% ( 103 % )
$200
$15452
-34 ( 34 )
$ -26703 ( 26703 )
$576
$1700
$262
$99.75
36.00% ( 36.00 % ) 2013 36.63% ( 36.63 % )
$155596
$32.26
-2420 ( 2420 )
$44.04
$151
$230000
$272
-2764 ( 2764 )
-94361099 ( 94361099 )
$185
$39.71
-100 ( 100 )
$369.10
$10.90
$16890
$4570
$125385
-1 ( 1 )
$16069
$ -4.10 ( 4.10 )
-90 ( 90 )
$77.50
$118
28.9% ( 28.9 % )
$180
$20743
$0.70
$20409
$225.00
-
( in thousands )
-3 ( 3 )
-38 ( 38 )
$100.00
30% ( 30 % )
100% ( 100 % )
$39
-415 ( 415 )
-22 ( 22 )
$141
-1677 ( 1677 )
$0.96
$121.50
$2.53
$1736
$5742
$111.80
$2101046
$170.10
$ -485 ( 485 )
$2.30
$2867
$87.76
$57369
-2.3 ( 2.3 )
$0
$14151
April 1 2025
$218883
-122 ( 122 )
$5031
1% ( 1 % )
$2076.80
$1.10
$791.00
$6705
$188
-5.5 ( 5.5 )
$5363
$56523
$1226.90
( 3.5 ) % ( % )
$146865
$6040
$ -28 ( 28 )
$4.50
$64.68
-14.6 ( 14.6 )
-157 ( 157 )
$181
*
Nov . 2000
$75.90
-51873773 ( 51873773 )
$2371
2.7% ( 2.7 % )
$5960
-1 ( 1 )
$2690.00
-20 ( 20 )
solar
$120.32
$6514604
4.65% ( 4.65 % )
-2042 ( 2042 )
$43.20
$6930
121% ( 121 % )
$1289286
$ -30 ( 30 )
$1531000000
$ -4132 ( 4132 )
$22561
-125 ( 125 )
$1451
$11
21% ( 21 % )
-35.4 ( 35.4 )
19.9% ( 19.9 % )
-3239 ( 3239 )
$2014
$ -500634 ( 500634 )
$9230
-4969 ( 4969 )
$25.09
$2274.50
-69 ( 69 )
4.53% ( 4.53 % )
$500
$4.66
1.35% ( 1.35 % )
-141 ( 141 )
$174456
-
$47
$6735
$3338
$9921
-380 ( 380 )
$52443
$ -279 ( 279 )
$4416
-8227 ( 8227 )
$3431
$2251.20
$66.38
-10.3 ( 10.3 )
$6525
$652
$6205
$146.49
$23295
$135.63
$22.28
-1523 ( 1523 )
$3832573
-120 ( 120 )
-46 ( 46 )
$1070.00
-21796 ( 21796 )
$ -
$11
-20760 ( 20760 )
-587 ( 587 )
$1177978
$6224.30
-11 ( 11 )
$181474975
2.61% ( 2.61 % )
-8893 ( 8893 )
$8782
$2063
-10 ( 10 )
$93.01
$2200
$8181
$108249
-1167 ( 1167 )
0.3% ( 0.3 % )
$58
$100
$19900
-1.4 ( 1.4 )
-7936 ( 7936 )
panama
owned
-70 ( 70 )
$4563
$102
-38.5 ( 38.5 )
$262
$8.89
-6001 ( 6001 )
$157.11
$116
-40 ( 40 )
$280064
-
40% ( 40 % )
-200793 ( 200793 )
$912926
$3581
$227400
$143
$242
$34.93
$56.70
-2650733 ( 2650733 )
$172
$696.30
$989
$ -8051 ( 8051 )
-86 ( 86 )
$287
-23.3 ( 23.3 )
$111.26
98% ( 98 % )
$93
$156259
buchanan ny
$17018
-20 ( 20 )
-8.7 ( 8.7 )
$15
-35 ( 35 )
other
$26.59
$1100.60
$105809
-15.9 ( 15.9 )
-4969 ( 4969 )
$31384
class c ( series i )
$10371
-5 ( 5 )
$68.10
-209 ( 209 )
-98 ( 98 )
$132.10
-24 ( 24 )
$118
$205.05
$3483072
70% ( 70 % )
$96161
$328
$399928
$120.19
-3582 ( 3582 )
$170.79
-119 ( 119 )
-9899 ( 9899 )
-2 ( 2 )
51.5% ( 51.5 % )
$135.60
$2518
$512
-10242 ( 10242 )
14% ( 14 % )
-637 ( 637 )
$115.26
-154 ( 154 )

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

-30 ( 30 )
$27.90
$1005.30
$39
$1
$29132
$2420
$41895
-1 ( 1 )
-221.6 ( 221.6 )
uganda
$82.50
$4674
104% ( 104 % )
$355300
$18645
$247.20
$40
$9362.20
nan
$193101
$3649
$677
-459 ( 459 )
28.00% ( 28.00 % )
-23 ( 23 )
-1598 ( 1598 )
$2.80
$5792
1.2% ( 1.2 % )
$13931
$12569
$319.50
$134.40
1.89% ( 1.89 % )
December 2003
$22956
-
$12042
$2470
$12926
June 30 2009
$84715
-2 ( 2 )
-8253 ( 8253 )
$99989339
$78
$3851
-1580 ( 1580 )
May 27 2014
$6980
December 2003
2014 2013 2015
$2583
$878.70
-15322 ( 15322 )
$4985
$7
$324590
$79.77
$148
-571 ( 571 )
$77.77
$163
$766727
28% ( 28 % )
$121.73
$262.90
$30
-81 ( 81 )
$154.61
-309026 ( 309026 )
25% ( 25 % )
$156029
-28.1 ( 28.1 )
$3077509
4% ( 4 % )
$111
36% ( 36 % )
bulgaria
-209 ( 209 )
-33 ( 33 )
-15.7 ( 15.7 )
$197383
$139.23
-550 ( 550 )
-
-58 ( 58 )
$85
18.9% ( 18.9 % )
$16.40
$55.00
$1290
-5.4 ( 5.4 )
$35624
4.0% ( 4.0 % )
high
-24 ( 24 )
$2014
-
-5.4 ( 5.4 )
$140
$116.40
nm
$13462
-4 ( 4 )
-1.1 ( 1.1 )
$2.91
$100.00
40% ( 40 % )
-131.1 ( 131.1 )
-106 ( 106 )
wind
$21780
-41 ( 41 )
$19
$15721
properties
-959.8 ( 959.8 )
$11831
$252000
-27 ( 27 )
-413 ( 413 )
$7351
-
$100.00
$ -1966 ( 1966 )
-53 ( 53 )
$148.98
-1105 ( 1105 )
$825.00
global institutional global industrial
$15415
-35 ( 35 )
$3777
$ -643 ( 643 )
$47.72
$89.24
-6 ( 6 )
class c ( series i )
3.0% ( 3.0 % )
*
$ -6129 ( 6129 )
-37 ( 37 )
47% ( 47 % )
actual
-
$49.20
$0
$1529.80
$31
$104681
-17 ( 17 )
$12259
$65.70
-626 ( 626 )
$ -91.3 ( 91.3 )
-2913 ( 2913 )
$100.00
$101438
$2577
1.1% ( 1.1 % )
-
$44.30
-18 ( 18 )
$117.48
-212 ( 212 )
$1553815
-54.1 ( 54.1 )
-5 ( 5 )
$34
-18607 ( 18607 )
-9 ( 9 )
-5 ( 5 )
$331.10
$9.32
-505 ( 505 )
34.9% ( 34.9 % )
turkey
$9263
$12516
$7367
-16 ( 16 )
-27.9 ( 27.9 )
$2693
$101.88
$196
$169.70
$52.69
operating
1.85% ( 1.85 % )
$3410
-418 ( 418 )
-18 ( 18 )
0.16% ( 0.16 % )
-
$4526
plymouth ma
-17677 ( 17677 )
$16.04
-413895 ( 413895 )
plymouth ma
$1847.80
$1169
$124
$550234
$175.00
-414.9 ( 414.9 )
$0.96
$26.00
$53.75
-32.0 ( 32.0 )
-2682 ( 2682 )
$114
$1800
*
$72.90
-9 ( 9 )
3.4% ( 3.4 % )
1.80% ( 1.80 % )
$102.10
coal
-29.4 ( 29.4 )
17.2% ( 17.2 % )
-807 ( 807 )
$3.16
$2880
$79.51
$221.91
1.44% ( 1.44 % ) 2013 3.05% ( 3.05 % )
-
operating
-43.3 ( 43.3 )
1% ( 1 % )
50.6% ( 50.6 % )
-267 ( 267 )
$0.20
$112
-366388 ( 366388 )
-250.1 ( 250.1 )
$11.10
$185500851
$755
$100
57.9% ( 57.9 % )
$3185
$521.60
$33.30
4.98% ( 4.98 % ) 20145.05% ( 20145.05 % )
$50.00
$30774
$301.96
$58.20
$ -4579.6 ( 4579.6 )
-271 ( 271 )
-
-8183 ( 8183 )
$5587388
-509 ( 509 )
2.6% ( 2.6 % )
$208.06
$511.30
-11 ( 11 )
$22878
$115
$1110.60
$2013
$ -
$1510
$140342
$351
-84.7 ( 84.7 )
$1400
4.62% ( 4.62 % )
204% ( 204 % )
$2281.80
$1637
$61900
0.29% ( 0.29 % ) - 0.44% ( 0.44 % )
-0.5 ( 0.5 )
-
-10.0 ( 10.0 )
3.22% ( 3.22 % ) - 4.40% ( 4.40 % )
9.9% ( 9.9 % )
-15.2 ( 15.2 )
$6166
-13 ( 13 )
21.2% ( 21.2 % )
$2014
$83.69
-17 ( 17 )
$52.13
35.83% ( 35.83 % )
-340 ( 340 )
$10.87
-212 ( 212 )
-306 ( 306 )
$ -9.0 ( 9.0 )
$138
-142.5 ( 142.5 )
$93.98
$429.20
-3793 ( 3793 )
$8654
$105409
-385.1 ( 385.1 )
$229.31
$17.30
$ -3.5 ( 3.5 )
$2041
-800 ( 800 )
$68239
-117 ( 117 )
-418 ( 418 )
-6 ( 6 )
$4385.50
$3280
48% ( 48 % )
-1.8 ( 1.8 )
-0.7 ( 0.7 )
-3 ( 3 )
-145 ( 145 )
-4 ( 4 )
$824.80
$3925
-
-11 ( 11 )
9.6% ( 9.6 % )
-38 ( 38 )
$1222
3.13% ( 3.13 % )
-32.0 ( 32.0 )
$ -27447 ( 27447 )
$2915
( 9 ) % ( % )
-17 ( 17 )
-
$3.00
$ -5312 ( 5312 )
$821
$708
$127.10
$1.73
-1333 ( 1333 )
$114857
50.0% ( 50.0 % )
$190
$7211
$1422
$3516
-30.3 ( 30.3 )
$823
$657
-170 ( 170 )
$0.69
$109669
$29.80
$136800
$222302
-3 ( 3 )
$0.90
$28
$2909
-5 ( 5 )
$80
$229
-184 ( 184 )
-1 ( 1 )
-134 ( 134 )
$ -94 ( 94 )
$32.40
$101.79
$29432

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$ 1.6 billion
$311
$2423
$911.30
$148
6% ( 6 % )
4.70% ( 4.70 % )
1.07% ( 1.07 % )
-0.2 ( 0.2 )
$ -229 ( 229 )
$100.00
-589.2 ( 589.2 )
8.4% ( 8.4 % )
$541800
$ -
0.49% ( 0.49 % ) - 1.27% ( 1.27 % )
October 2004
-199.7 ( 199.7 )
$127.54
$160.23
global institutional
$2014
$647
-5 ( 5 )
$136098
-94 ( 94 )
$128.68
$15.10
-6062 ( 6062 )
$204.63
$1595
$17525
$354441
$13240
$123
33.54% ( 33.54 % )
$519
global headquarters and office space
$1666
-168 ( 168 )
57.1% ( 57.1 % )
$ -218 ( 218 )
-8 ( 8 )
-34 ( 34 )
$503
$555.30
12.63% ( 12.63 % )
$35
$140.54
$48845672
-489 ( 489 )
$181
-1390 ( 1390 )
$52.80
-13000 ( 13000 )
27% ( 27 % )
$1647903
-19 ( 19 )
$ -599 ( 599 )
$2161
-600 ( 600 )
15.8% ( 15.8 % )
109% ( 109 % )
-
liv
$1127588
$112
$1703.40
$ -247587 ( 247587 )
$9856
$267
-0.1 ( 0.1 )
$624
$115
-
nan
-19 ( 19 )
-91203780 ( 91203780 )
$622
-5.2 ( 5.2 )
$15
$ -30741 ( 30741 )
$120997
-285 ( 285 )
$1828519
-5 ( 5 )
$100.00
-828 ( 828 )
$197.58
$1642.10
$2310.20
$16.60
$1546
$43
$7215
nan
$540
5.53% ( 5.53 % )
-10.1 ( 10.1 )
-61 ( 61 )
$0.10
$1074.50
-
-3.6 ( 3.6 )
-72.1 ( 72.1 )
-445 ( 445 )
-148 ( 148 )
-265718 ( 265718 )
-.1 ( .1 )
$343
36.4% ( 36.4 % )
$449.00
$169604
$519
$14001
$1199
$6161
$91
$279
3% ( 3 % )
$ -0.07 ( 0.07 )
-20 ( 20 )
$414.58
( in thousands )
28% ( 28 % )
-
$831.20
$175
$6424582
$1686
$86.21
-270 ( 270 )
-129359 ( 129359 )
$207
-5934 ( 5934 )
$100
$ -
$275305
-39 ( 39 )
-1097 ( 1097 )
$214
$10410
$ -163 ( 163 )
$7230
$345
$9076
$158.46
$ -98 ( 98 )
-2 ( 2 )
$100
filer city mi
2% ( 2 % )
-7794 ( 7794 )
$5728
$22.70
$ -815.1 ( 815.1 )
$29010
$24.70
$3151
$11.00
$216
$3.55
$1548.20
$167.70
-1403826 ( 1403826 )
-272 ( 272 )
4.5% ( 4.5 % )
$129
-86 ( 86 )
turkey
$0.19
$28.70
$787613605
$297.80
office space
$299
$2014
$399
$8215
-627 ( 627 )
$28
$161394
0.10% ( 0.10 % ) - 1.05% ( 1.05 % )
$2182419
-1292 ( 1292 )
$2441
$189.57
$2368
$967084
70% ( 70 % )
$747246
$1300
21.40% ( 21.40 % )
$1720
28.51% ( 28.51 % ) 2013 35.30% ( 35.30 % )
china
$100.00
$669
$84
-31.0 ( 31.0 )
$8435
-91 ( 91 )
nan
$ -34 ( 34 )
$76.90
$7757
$3609
$22.79
$118.50
-14.0 ( 14.0 )
$28.21
$13.45
$112125
-9 ( 9 )
-2623 ( 2623 )
-0.5 ( 0.5 )
$78.71
$18516
$2028
-16.9 ( 16.9 )
$ -243 ( 243 )
-8557 ( 8557 )
11% ( 11 % )
chile
$147
$993
$1735.50
-6682 ( 6682 )
owned
$132
40% ( 40 % )
4.00 years
$155459545
-
$7789
$1.40
$100
-25 ( 25 )
$6942
-784 ( 784 )
$120
6% ( 6 % )
-104 ( 104 )
$2480
-930 ( 930 )
$939.80
53.0% ( 53.0 % )
-1889 ( 1889 )
$26.00
$323558
218% ( 218 % )
$179840
-592 ( 592 )
owned
$4036
$98.05
$163
$45296
-9500 ( 9500 )
-
$73.18
$124.30
4.08% ( 4.08 % )
$6
$293.90
$1637
$71
$14859.70
-$6.30
$11482
$100
$148.90
$ -1289 ( 1289 )
43% ( 43 % )
$7.28
$102.57
$212958
$10
$70
43.5% ( 43.5 % )
$7.81
$1000000
$268
$90643
-6.4 ( 6.4 )
$195.75
-82 ( 82 )
-628 ( 628 )
11.2% ( 11.2 % )
$33
-1.6 ( 1.6 )
construction
$38280
-8 ( 8 )
$727.00
$52855
$508
$426
$6427
-1547 ( 1547 )
$152.55
-190 ( 190 )
$4066
-31674085 ( 31674085 )
-157 ( 157 )
-999 ( 999 )
21.7% ( 21.7 % )
$19011
-10 ( 10 )
$88
( 19 ) % ( % )
$2014
$254
-87 ( 87 )
$ -23158 ( 23158 )
$672
-2377 ( 2377 )
$13520
$10.02
-6.6 ( 6.6 )
$2643
Nov . 2012
$165.80
$135
( 1.3 ) pt
$126067
-935 ( 935 )
$1219
$1842
-14.1 ( 14.1 )
$245029
$4462
$114.10
wind
$10
$3.27
-2 ( 2 )
-8 ( 8 )
$25544
$51.00
$ 2.5 billion
9% ( 9 % )
$7670
-195.9 ( 195.9 )
-209 ( 209 )
$ -258 ( 258 )
class c ( series iv )
$111
$57665
April 1 2017
10.7% ( 10.7 % )
-138.7 ( 138.7 )
-5 ( 5 )
5% ( 5 % )
$90.29
2.4% ( 2.4 % )
-20.2 ( 20.2 )
$2634
$104520
$1587
-607.5 ( 607.5 )
$2550
$4528
$118560581
-2638 ( 2638 )
$27683
$967.90
-
$14286
-3 ( 3 )
-3734 ( 3734 )
$220.70
-5 ( 5 )
$946848
39% ( 39 % )
$619
*
$97.44
$36.25
( 2.7 ) % ( % )
$14685
$20.00
$10014
$9840
72% ( 72 % )
*
35.0% ( 35.0 % )
$401442
transfers in and/or ( out ) of level 3
$6226
$8732
$197.80
32.7% ( 32.7 % )
$352
$838
$1900
$16.10
$9276
$0.76
$19837
$36.63
$122300000.00
$2894
$6930381
$ -3391 ( 3391 )
$142.07
-441.5 ( 441.5 )
$18030
-145 ( 145 )
-34 ( 34 )
-38 ( 38 )
nyiso
united states
-107 ( 107 )
-48448 ( 48448 )
$2717
$153.54
1.7% ( 1.7 % )
$825
$174957
$102
9.4% ( 9.4 % )
-158 ( 158 )
$1733
-443.0 ( 443.0 )
global institutional global industrial
$145.30
1% ( 1 % )
-37 ( 37 )

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$25621
$2291520
$2142045
-198 ( 198 )
-
$201
50.1% ( 50.1 % )
-156 ( 156 )
$14810
-1.6 ( 1.6 )
$ -6600 ( 6600 )
-67 ( 67 )
$0.42
$100
$379
$2.25
-
$31.45
0.91% ( 0.91 % )
2.3% ( 2.3 % )
$3231.60
-91 ( 91 )
$187789
$16069
$16009
$8203
$108.70
$35.73
-1077 ( 1077 )
-1.9 ( 1.9 )
$106116
1.6% ( 1.6 % )
$1385
-3789 ( 3789 )
-10 ( 10 )
$10657
$43.30
$ 522 million
14.5% ( 14.5 % )
$2560
-38286 ( 38286 )
$4863
$11582
-31156 ( 31156 )
$9943
$110.31
$3609
$18508
-19.8 ( 19.8 )
-
$9127
-25 ( 25 )
$5369
$50583
$ -4332 ( 4332 )
coal
79% ( 79 % )
23.71% ( 23.71 % )
$446.40
$ -34 ( 34 )
$4910
$225.95
$7147
-
$63.91
$5940
$3111
-6.8 ( 6.8 )
-5.1 ( 5.1 )
-73 ( 73 )
$60.15
$2021
-28853 ( 28853 )
21.7% ( 21.7 % )
-25 ( 25 )
-195 ( 195 )
-31 ( 31 )
$74.86
-9965 ( 9965 )
$5303
-860 ( 860 )
$137
-21.1 ( 21.1 )
6.75% ( 6.75 % )
$512
$7510
$1235
-97 ( 97 )
$217.56
$4303
-92 ( 92 )
-0.2 ( 0.2 )
1041 mw - pressurized water
-51186 ( 51186 )
$213
$350
( 9 ) % ( % )
$5890
-0.1 ( 0.1 )
-5.7 ( 5.7 )
$200.00
$355
-
-65468 ( 65468 )
sept . 2001
$ -2674 ( 2674 )
$19.67
2.7% ( 2.7 % )
$376
$1131
-1 ( 1 )
$100
-55 ( 55 )
15% ( 15 % )
$100.00
-1 ( 1 )
$26
$61661
-
$97
$33584
-178 ( 178 )
$130
-706 ( 706 )
$32.68
$125.92
$2.44
-35655 ( 35655 )
$2355
$4618
$22176
$128.00
$ -208 ( 208 )
-33869 ( 33869 )
$101.76
115% ( 115 % )
-89 ( 89 )
$83.03
$41.50
$54
$141334
$1252
$ -435 ( 435 )
-
-205 ( 205 )
$3080
-9 ( 9 )
$100.00
$ -78 ( 78 )
$175.21
$1700
$2553
$1.86
$0.40
-1982560 ( 1982560 )
$ -1663 ( 1663 )
nan
$37
-141.6 ( 141.6 )
4.8% ( 4.8 % )
nyiso
-93.0 ( 93.0 )
nan
$20.06
14% ( 14 % )
$172.30
-147 ( 147 )
$592.90
$ -2258 ( 2258 )
$51.00
$19520
-74.3 ( 74.3 )
-322 ( 322 )
$23.41
-8 ( 8 )
$58.82
$62.25
$ -2008 ( 2008 )
$100
$57536
-49 ( 49 )
$148887
$2
-15762 ( 15762 )
$ 15.2 million
$91798
$91000
-6 ( 6 )
119% ( 119 % )
$15395
$ -126.3 ( 126.3 )
$186
$6.99
$18874
-0.8 ( 0.8 )
$100.00
$1265843
$131
$134
$98.20
$690.60
$1.20
$170.70
$100.00
-37.5 ( 37.5 )
$7.20
-95.5 ( 95.5 )
21% ( 21 % )
$682
-173006 ( 173006 )
$186.17
$735.70
$17118
$98821
-32.1 ( 32.1 )
0.08% ( 0.08 % )
-182.9 ( 182.9 )
-79 ( 79 )
-1 ( 1 )
$132
-21 ( 21 )
-81 ( 81 )
$7.20
$ -16621 ( 16621 )
28% ( 28 % )
-2953 ( 2953 )
$35066
-2 ( 2 )
-11 ( 11 )
$2122
$ -8.99 ( 8.99 )
$8
-4474 ( 4474 )
$323.60
$28484
$5308
-558 ( 558 )
-
-
-605 ( 605 )
3.80% ( 3.80 % )
$2237
$308263
-16.0 ( 16.0 )
$726.60
-142 ( 142 )
129% ( 129 % )
$306
$100.00
$20.54
$18181
$120.40
$39.20
9.1% ( 9.1 % )
$135.90
$10580
$160468
-3357.5 ( 3357.5 )
$3725
$1732
$265.06
$28.60
-36 ( 36 )
-
$0.07
$55
-1 ( 1 )
-323382 ( 323382 )
$1562.10
$217.60
$4169061854
$78.70
-10 ( 10 )
$2.20
$4501
$6723
$413
$ -
$512.80
-6 ( 6 )
1.1% ( 1.1 % )
-18195 ( 18195 )
$17.07
$396
$92.98
$125
-4928 ( 4928 )
-18073 ( 18073 )
February 12 2014
$2832
$100
-.3 ( .3 )
34% ( 34 % )
-22.4 ( 22.4 )
$942.10
$50.96
$3717.00
-43.6 ( 43.6 )
$1321
-21 ( 21 )
$17387
$56.45
63.8% ( 63.8 % )
$1170
5.6% ( 5.6 % )
$7991
$100.00
-1074 ( 1074 )
$65.31
98% ( 98 % )
$641
$387.90
$1732
$57.76
$169123
years
$295
-127.7 ( 127.7 )
$8261
-1.3 ( 1.3 )

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

( in thousands )
$357.20
$17.00
-540 ( 540 )
-303 ( 303 )
$ -0.4 ( 0.4 )
$2
-4.5 ( 4.5 )
-275.6 ( 275.6 )
--
-3.2 ( 3.2 )
35.0% ( 35.0 % )
-15 ( 15 )
$795000
$4698
$3326
21.6% ( 21.6 % )
2013 ( c )
-849 ( 849 )
$45.30
5.0% ( 5.0 % )
$0.10
$1058
$160
$100.00
$33.20
lower ccg operating expense
$63.40
$442
$7632
0.7% ( 0.7 % )
$56.17
*
$122
-
$1053
$135.20
$2605
27% ( 27 % )
$273
-225 ( 225 )
0.7% ( 0.7 % )
-
-40 ( 40 )
$317
-80 ( 80 )
-140 ( 140 )
-732 ( 732 )
-4969 ( 4969 )
139% ( 139 % )
$ -16.5 ( 16.5 )
$72.25
-45.4 ( 45.4 )
6 months
$84.87
$11448
$29616
-1016 ( 1016 )
-41 ( 41 )
$78.53
$176675
$1519183
-200.8 ( 200.8 )
46% ( 46 % )
-646560 ( 646560 )
$17875
5.08% ( 5.08 % )
$13
3.29% ( 3.29 % )
-16.9 ( 16.9 )
4.2% ( 4.2 % )
-4145 ( 4145 )
-194.2 ( 194.2 )
$20.60
$104.24
-134 ( 134 )
( 93.8 ) % ( % )
65% ( 65 % )
$73597
$278
$ -
$1.56
$38384
-105.9 ( 105.9 )
--
-
-30 ( 30 )
-44247 ( 44247 )
$3.10
$311
$188.30
-4 ( 4 )
$55.74
$110
$22926
( 5.5 ) pt
$17775
-
$14.17
$12676
$10519
-232 ( 232 )
-1474 ( 1474 )
-156 ( 156 )
$2649
$95.11
$50408
-100 ( 100 )
$178.30
-643 ( 643 )
-476 ( 476 )
$13
$121251
$12
-255 ( 255 )
$217
$81570
( 1.6% ( 1.6 % ) )
$97.50
$766
$41.26
$1.40
--
$1351.00
-1978 ( 1978 )
$593706
$16117
-1557 ( 1557 )
-1102 ( 1102 )
$36885
$ -8.99 ( 8.99 )
$ 2.0 billion
$19018
gas
$102.11
$742
$60
$100
$ -1298.9 ( 1298.9 )
$831427985
$283.02
$3601.80
6 months
-1365 ( 1365 )
$111
-15.6 ( 15.6 )
$114.39
$19087
$29321
$20598
$62600
$145.53
-
$227368014
$92
$1208430
$36.23
-600.0 ( 600.0 )
$9926
-257 ( 257 )
$17000
-
$240.90
8.0% ( 8.0 % )
-594 ( 594 )
.22% ( .22 % )
-12 ( 12 )
201% ( 201 % )
$50.49
$198.06
-47.9 ( 47.9 )
$3.52
$576900
-82 ( 82 )
$ -3258 ( 3258 )
$ 1.2 billion
$151202
-7 ( 7 )
$1631
-7.5 ( 7.5 )
$135643
$45.80
-892 ( 892 )
-9.6 ( 9.6 )
$27.53
$29.10
-9.1 ( 9.1 )
$31739
$1229
$17365401
$104
-481 ( 481 )
$781
$116.10
$87.45
3.73% ( 3.73 % )
2.8 years
$1252
$139.80
$41.26
$2081
$1586.20
-7.0 ( 7.0 )
$30809
$3553
$181
-
shed
$85
$28.60
$12328
$70.31
-29 ( 29 )
30.0% ( 30.0 % )
$8066
3% ( 3 % )
$560193
$148716
$16.63
$9640
2028 ( 4 )
-
$14673
$330.00
$9889
-6 ( 6 )
$ -10.4 ( 10.4 )
$17590
-71063 ( 71063 )
42% ( 42 % )
$582
$1.00
$80406
-115 ( 115 )
$171.04
$174
-24 ( 24 )
293% ( 293 % )
construction
$197
-2426 ( 2426 )
-2346 ( 2346 )
-70 ( 70 )
$33725
$140.50
-224 ( 224 )
7.7% ( 7.7 % )
$180.17
$ -11975 ( 11975 )
$94417
58.3% ( 58.3 % )
$16087
-35.4 ( 35.4 )
$11653
sept . 2014
$4608
$25.40
0.0 to 0.25
colombia
$191
-1 ( 1 )
$20098
-11 ( 11 )
-317 ( 317 )
$24
$2300
-9 ( 9 )
$680
$416956
$18447
$270
$3.90
$35.10
-7 ( 7 )
$ -
( 21 ) % ( % )
$1044
$2014
$150
$1303
$133.79
24.0% ( 24.0 % )
$7860
$23.93
$271577
-
-440 ( 440 )
22.10% ( 22.10 % )
$1451
$703
$60
$ -1.5 ( 1.5 )
-1419840 ( 1419840 )
$155
50% ( 50 % )
$ -83.2 ( 83.2 )
1.0% ( 1.0 % )
15.05% ( 15.05 % ) - 17.18% ( 17.18 % )
$6598
$7339
-
-3.0 ( 3.0 )
-5372 ( 5372 )
-24 ( 24 )
-2.4 ( 2.4 )
$26.50
19.6% ( 19.6 % )
$4845
-415 ( 415 )
$100
$998.70
-14060 ( 14060 )
16% ( 16 % )
$44
$18
$516019
$295
$ -50 ( 50 )
-128.1 ( 128.1 )
$4920
-220883 ( 220883 )
$61.25
$6190
$43818
$1786.20
$6581
-409 ( 409 )
.57% ( .57 % )
$9811
$ -4027 ( 4027 )
-10.2 ( 10.2 )
$ 371 million
$2258.80
$12613
$35517
$ -6.1 ( 6.1 )
$10430
-1 ( 1 )
nan
-305 ( 305 )
-5 ( 5 )
$1833
February 25 2014
$800463
-20 ( 20 )
15.41% ( 15.41 % ) - 16.04% ( 16.04 % )
$175
-10.8 ( 10.8 )
-869925 ( 869925 )
cash
$51
$5834.60
-56 ( 56 )
$6506.90
-1417.7 ( 1417.7 )
$100.00
$74
$736.90
$130
6% ( 6 % )
-14.0 ( 14.0 )
owned
$54213
$217.49
million
-720 ( 720 )
4.2% ( 4.2 % )
-746 ( 746 )
-12034 ( 12034 )
-0.4 ( 0.4 )
-7 ( 7 )
leased
$650.50
-6047 ( 6047 )
$2224
16.7% ( 16.7 % )
$0.88
$7983
$47369
$3.22
$2014
$2111
$14.00
$161
20% ( 20 % )
-819 ( 819 )
$ -35.5 ( 35.5 )
-3823 ( 3823 )
$189
$ -1141879 ( 1141879 )
$ -
$629
0.38% ( 0.38 % )
$1491
$1032
operating
$182.70
$348.30
1.7% ( 1.7 % )
$7153
-22234 ( 22234 )
$130.80
-
$ -1.56 ( 1.56 )
$516
$49.60
$13295
$94.15
-0.8 ( 0.8 )
2017 $ 898
$135.40
-294 ( 294 )
-
0.7% ( 0.7 % )
$2.54
$27.24
-1982 ( 1982 )
-310 ( 310 )
$14.17
$2066
$ 1.3 billion
-1 ( 1 )
-49471 ( 49471 )
-5.5 ( 5.5 )
$21.07
-
$215
$20500
$2071
$8027
$158.05
$13267
37.98% ( 37.98 % )
class c ( series iii )
-11.9 ( 11.9 )
$121.48
9% ( 9 % )
global institutional global industrial
$20202
$8.20
$298.31
$1642438
$9202
leased
11.12% ( 11.12 % )
-7.4 ( 7.4 )
-
-24.9 ( 24.9 )
$5342
$0.70
$56.29
-13257 ( 13257 )
$287.71
( in thousands )
$ -142 ( 142 )
-1.3 ( 1.3 )
-35 ( 35 )
$110.23
$232
-1.2 ( 1.2 )
-38126 ( 38126 )
3.6% ( 3.6 % )
-54 ( 54 )
$ -
$881.80
35.00% ( 35.00 % )
-212 ( 212 )
$1169
July 2002
-2674 ( 2674 )
$26677
10.9% ( 10.9 % )
$100.00
$5450
August 2003
-17 ( 17 )
$9037
-477 ( 477 )
-10.8 ( 10.8 )
$129
20% ( 20 % )
$ -2182 ( 2182 )
$514177
$1011
0.25 to 0.5
-37 ( 37 )
-382 ( 382 )
$1579
$350.82
owned
$27.29

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$14.17
-1 ( 1 )
$4347
-11 ( 11 )
-33 ( 33 )
$25042
$23.77
$173
-0.4 ( 0.4 )
-872 ( 872 )
$2.10
13% ( 13 % )
-22 ( 22 )
21% ( 21 % )
-1 ( 1 )
$195.00
-4 ( 4 )
$179.33
$20435
$541
sept . 2001
22% ( 22 % )
expiring in 2009
$19686
-27 ( 27 )
-
52% ( 52 % )
$159.23
$4844
$237500
$113047
$6.42
-10 ( 10 )
$2.83
-2397 ( 2397 )
4.1% ( 4.1 % )
$3276
-85 ( 85 )
$390.00
35.26% ( 35.26 % )
December 2003
$24.19
-2192 ( 2192 )
-18 ( 18 )
$16.20
-719 ( 719 )
$13670
-45 ( 45 )
$74
$14.70
$1036
-1774 ( 1774 )
-17 ( 17 )
$13.91
-92 ( 92 )
-21 ( 21 )
-27 ( 27 )
96% ( 96 % )
$456
$6.60
$78
6.25 years
November 30 2019
% ( % )
-4.6 ( 4.6 )
-14 ( 14 )
$39.72
-191288 ( 191288 )
$882
14.9% ( 14.9 % )
$72.77
$115.65
$63.44
$6363
$1665
-9818 ( 9818 )
21% ( 21 % )
-6694 ( 6694 )
$ -58440 ( 58440 )
3.75% ( 3.75 % ) above 6-month libor
$462
$284.75
-31.8 ( 31.8 )
$7.10
-11869 ( 11869 )
-22705 ( 22705 )
$7106
-685 ( 685 )
$12.50
688 mw - boiling water
-3646 ( 3646 )
$5720
$88.50
35.0% ( 35.0 % )
$144.58
$5077
$135
-1.2 ( 1.2 )
2032 ( 2 )
$3400
$179.10
15.0% ( 15.0 % )
-8.0 ( 8.0 )
$807
-10.1 ( 10.1 )
$207
( 6 ) % ( % )
7.75% ( 7.75 % )
-56 ( 56 )
190% ( 190 % )
$158.07
-80 ( 80 )
$230
-1 ( 1 )
-47 ( 47 )
low
$111.99
-70 ( 70 )
-26786 ( 26786 )
$165.75
$482.60
$51
-8244 ( 8244 )
-1181249 ( 1181249 )
$887.30
$14.38
1.6% ( 1.6 % )
-19 ( 19 )
55% ( 55 % )
$ -13 ( 13 )
1.450% ( 1.450 % )
$93.10
$713
-324 ( 324 )
-515 ( 515 )
$4172.00
$10379
.35% ( .35 % )
26% ( 26 % )
$0.06
-49 ( 49 )
cash
$ -143.4 ( 143.4 )
-
1028 mw - pressurized water
$1252.30
1.41% ( 1.41 % ) 2013 2.04% ( 2.04 % )
$1961
$1512
$162
$2301.60
-11864 ( 11864 )
$725413
$35
-154.0 ( 154.0 )
-1.3 ( 1.3 )
-
-
$21.60
$1069
-18 ( 18 )
-19.5 ( 19.5 )
$24
-633 ( 633 )
-
$ -3.79 ( 3.79 )
31% ( 31 % )
-639 ( 639 )
2032 ( d )
$8367
-53515 ( 53515 )
$43.05
119% ( 119 % )
-1 ( 1 )
$23
-
$166.80
688 mw - boiling water
-23 ( 23 )
-
$19223
3.4% ( 3.4 % )
$107.20
$14.60
$103
-8.8 ( 8.8 )
20.45% ( 20.45 % )
-22921 ( 22921 )
May 8 2014
31% ( 31 % )
-
-2332 ( 2332 )
22.0% ( 22.0 % )
$600883
0% ( 0 % )
$2408.80
$100.00
-30.6 ( 30.6 )
20.1% ( 20.1 % )
$55
$100.00
$270
-7 ( 7 )
$117
-56 ( 56 )
-21.2 ( 21.2 )
$103.60
-680 ( 680 )
$147
$500097
-120 ( 120 )
$4063
$221.68
$71
$3
-173165 ( 173165 )
$631
-
$6817
3.5% ( 3.5 % )
28.8% ( 28.8 % )
$59.25
3.81% ( 3.81 % )
-0.2 ( 0.2 )
-45.4 ( 45.4 )
$4484
$38
-1 ( 1 )
$1130.70
-4 ( 4 )
43.3% ( 43.3 % )
$178.89
$163607
-1125 ( 1125 )
-8 ( 8 )
$0.81
$5692
$20.29
$100.00
$7320
$21895
$139.29
$8.30
-78 ( 78 )
$35.01
$20397
3.0% ( 3.0 % )
$1703
$100.00
-27 ( 27 )
$69.36
hydro
27.7% ( 27.7 % )
$78.40
-
$38.02
$846258
-13 ( 13 )
0.6% ( 0.6 % )
-446.7 ( 446.7 )
-4.9 ( 4.9 )
-60 ( 60 )
$170
( in thousands )
-30593 ( 30593 )
-226 ( 226 )
9.0% ( 9.0 % )
-12461 ( 12461 )
2034 ( b )
$68
-3 ( 3 )
$5002
-8.8 ( 8.8 )
$35653
$5729.20
$7430
$161113
-
-23 ( 23 )
-17 ( 17 )
$1398
$30.75
$3988
$100.00
-514 ( 514 )
$15.93
$74.60
$3804
$4685
0.3% ( 0.3 % )
-2789 ( 2789 )
$ -2369 ( 2369 )
$42.64
$529370
-
$2014
$2818
1.23% ( 1.23 % )
$148
-2738 ( 2738 )
-1 ( 1 )
$282
$ -827 ( 827 )
Nov . 2000
$86.35
$43.05
$1047
$100
$100
-2351 ( 2351 )
$772
$8763
$162070
60.2% ( 60.2 % )
$48.50
-155.6 ( 155.6 )
-51 ( 51 )
$943
-22238 ( 22238 )
$180618
$63
$124504
$28886
$ -359 ( 359 )
-20 ( 20 )
-
5.0% ( 5.0 % )
-10 ( 10 )
$152
-8.1 ( 8.1 )
-8 ( 8 )
-11 ( 11 )
$384102
$95.20
2.2% ( 2.2 % )
$6.10
$0.40
$327.63
$4285284
$38
$82
$0.07
-19 ( 19 )
$28520
$382
-
-204 ( 204 )
$128.78
-917 ( 917 )
$860
$12880
$4105
$149.60
$13235
$92
$ -1163540 ( 1163540 )
-7964 ( 7964 )
$192.30
$14200
-
$2260
$968
$197
$2585
-29.9 ( 29.9 )
$15780
-17 ( 17 )
$438
$532
2% ( 2 % )
$846628
$385530
-2913 ( 2913 )
2.36% ( 2.36 % )
31% ( 31 % )
1.41% ( 1.41 % ) 2013 2.39% ( 2.39 % )
-5474988 ( 5474988 )
$187.74
$1038
$69.30
$3514
12.88% ( 12.88 % )
-561 ( 561 )
-8470 ( 8470 )
-367.9 ( 367.9 )
49% ( 49 % )
0.4% ( 0.4 % )
-4 ( 4 )
$87.45
11.9% ( 11.9 % )
million
$1472.60
$119.28
$2260
$37.40
$38.50
-11 ( 11 )
$308
-3.3 ( 3.3 )
$100
-232 ( 232 )
$630000
$24460
$5650
$158553178
0.7% ( 0.7 % )
$94
$8890
$8461
$3607539
$37237
$171
-91.0 ( 91.0 )
5% ( 5 % )
$74.86
$6147
$130.29
$2246.40
11% ( 11 % )
-225 ( 225 )
$195551133
$69.60
$4563
$464
$16.11
-$33
-3572 ( 3572 )
-268 ( 268 )
-
-11 ( 11 )
16.6% ( 16.6 % )
$2227
$2789.70
-94959 ( 94959 )
$114.02
$442.30
13.1% ( 13.1 % )
-1436 ( 1436 )
$277.03
$131777
$105.54
$344200
$102.87
$155371301
$2.68
-511 ( 511 )
-472 ( 472 )
$ -1269 ( 1269 )
$45.50
$681
$100.00
$163.72
-453 ( 453 )
-18 ( 18 )
$828250
-43 ( 43 )
$8850
$1750
$8700
$9914
$442
$55
( dollars in millions )
$63.20
$407
-12 ( 12 )
2.7% ( 2.7 % )

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

$200.00
$1294310
$62.20
19.3% ( 19.3 % )
-24 ( 24 )
$1258
$37112
$119
-279.6 ( 279.6 )
16.8% ( 16.8 % )
$7284
$1286
-102.5 ( 102.5 )
-21 ( 21 )
$62.42
$162
$20.00
-7 ( 7 )
-.3 ( .3 )
-5 ( 5 )
-2 ( 2 )
-16.1 ( 16.1 )
$52.30
-25817 ( 25817 )
$143043
$68
( dollars in millions )
1.90%-2.00% ( 1.90%-2.00 % ) above 3-month libor
$887
-25 ( 25 )
$29706
$1927
$1882
-20 ( 20 )
$10208
71% ( 71 % )
$5310
$553767
0.9% ( 0.9 % )
$103
-685 ( 685 )
$92.30
2021 to 2036
$1425
$38.30
-
$6115
33.7% ( 33.7 % )
$ -1.2 ( 1.2 )
$ -2689 ( 2689 )
$2696
$133.79
-
$2.00
purchases issuances and settlements
-4.5 ( 4.5 )
$150.00
2.64% ( 2.64 % )
$3557
-42 ( 42 )
-1155 ( 1155 )
$970.40
-
-2.3 ( 2.3 )
$ -40419 ( 40419 )
$6894
$46
-410.3 ( 410.3 )
( in thousands )
2.58% ( 2.58 % )
-12 ( 12 )
$697.20
-121.8 ( 121.8 )
-101 ( 101 )
$9299
$140.50
$111.31
$9878
$1472400
$223.42
-21.9 ( 21.9 )
$ -440 ( 440 )
$2014
$14362
$87.88
$852.10
-3887 ( 3887 )
$159
$1434
-121.8 ( 121.8 )
sbs nordic ( a )
-62 ( 62 )
-2179286 ( 2179286 )
-
$126.45
$2595
$257971
$5331
balance at december 31 2009
$ -1062 ( 1062 )
$250
second quarter
$538
$2014
$201
$244.50
$12.40
-
$66.34
$791
$30
-3721 ( 3721 )
$ -32 ( 32 )
$320078
-
-477 ( 477 )
owned
86.6% ( 86.6 % )
$509
$62801
$116.64
$831
$76.74
$ -5.95 ( 5.95 )
11.29% ( 11.29 % ) 2013 16.59% ( 16.59 % )
$5368
0% ( 0 % )
-99 ( 99 )
$16
$33.30
$52.32
$29497
$317
-44.3 ( 44.3 )
$77
$1327.60
352 ( d )
-39 ( 39 )
$52
$80.03
1.00% ( 1.00 % )
11% ( 11 % )
-
$133
-17 ( 17 )
12.8% ( 12.8 % )
$2013
-40 ( 40 )
$ -40 ( 40 )
7% ( 7 % )
0.34% ( 0.34 % )
$39171
$17500
$1938
$171.79
$1820
$663
-
lower ccg platform unit cost
$7
-5 ( 5 )
$2129
26% ( 26 % )
-1365 ( 1365 )
$156
$1688.40
$2014
$13053
5% ( 5 % )
$266
$2.30
$105
0% ( 0 % )
$5363
$58219
-2.8 ( 2.8 )
-556 ( 556 )
-32 ( 32 )
-6.7 ( 6.7 )
$ -450094 ( 450094 )
( 100.0 ) % ( % )
-5 ( 5 )
$2
$2078
$577869
-
bulgaria
$1.20
$2014
$ -10 ( 10 )
-68 ( 68 )
July 2002
$2832
-2740 ( 2740 )
$160
million
$2764
-31.2 ( 31.2 )
$92942
$19766
$ -1115 ( 1115 )
$157
$1531000000
-648 ( 648 )
-14.9 ( 14.9 )
$101
$7388
$1127
$25.40
$1993.70
$60.00
-210 ( 210 )
-41 ( 41 )
$172
$45366
$258.00
--
-35 ( 35 )
$ -53 ( 53 )
50% ( 50 % )
-142.0 ( 142.0 )
$4474
$11.50
higher gross margin from ccg platform revenue1
-30160 ( 30160 )
33.9% ( 33.9 % )
0.75% ( 0.75 % )
$39.43
$438967
6 months
-574 ( 574 )
$124.88
$1222
$40.64
-38932 ( 38932 )
-11 ( 11 )
$ -14108 ( 14108 )
$4969
-60 ( 60 )
-2 ( 2 )
-121 ( 121 )
$197
-1342 ( 1342 )
$1247.90
$3287121
$ -423 ( 423 )
-19 ( 19 )
6 months
-85.0 ( 85.0 )
$24.40
-602 ( 602 )
-4.0 ( 4.0 )
-
$46
$1898
10.9% ( 10.9 % )
$174.54
$1830
$2534.10
-5.7 ( 5.7 )
0.98% ( 0.98 % )
33.16% ( 33.16 % ) 2013 33.86% ( 33.86 % )
-149210 ( 149210 )
-25 ( 25 )
$142
is0-ne
$35764
$15.40
$15554
$2071
$135.20
-108716 ( 108716 )
80.6% ( 80.6 % )
$5836
$10387
$2459
199% ( 199 % )
-29 ( 29 )
$100.00
$3236
-
none
$9.98
70% ( 70 % )
-
$2013
-6094 ( 6094 )
$416
-66 ( 66 )
-50 ( 50 )
$ -0.4 ( 0.4 )
$15
$13504
4.4% ( 4.4 % )
$ -1.2 ( 1.2 )
$11.00
-32 ( 32 )
$214524
-389 ( 389 )
$ 2.6 billion
$5.80
included in other income ( expense )
95% ( 95 % )
-648 ( 648 )
$ -194628 ( 194628 )
$364221
-
-62 ( 62 )
-12.4 ( 12.4 )
$152.16
united kingdom
-527 ( 527 )
-94 ( 94 )
$59349
$8974
owned
December 2004
54.6% ( 54.6 % )
$1300
$6504
$1890.10
-66594 ( 66594 )
-6 ( 6 )
$3711
$111149
$3856
$1817
$911
-809 ( 809 )
$264755
32% ( 32 % )
45.2% ( 45.2 % )
$439
nyiso
$9714.10
-430 ( 430 )
$92197
$ -
-837 ( 837 )
-
-29.1 ( 29.1 )
$0.20
$111.65
$419962
$2240
8.7% ( 8.7 % )
-451.7 ( 451.7 )
$5531
3.1% ( 3.1 % )
$2.86
-23 ( 23 )
$151.44
$436.89
-849 ( 849 )
$398
26% ( 26 % )
$556
$153.90
-159 ( 159 )
$4314
32.20% ( 32.20 % )
$148.50
nan
-7.3 ( 7.3 )
$ -7606 ( 7606 )
$22561
$895
-16.8 ( 16.8 )
$0.50
-5739 ( 5739 )
$897367
-13.9 ( 13.9 )
-302 ( 302 )
$20956
-105 ( 105 )
-
$132
-3737 ( 3737 )
-3191.5 ( 3191.5 )
owned
$8500
-9 ( 9 )
$13029
November 30 2021
$108
$ -171590 ( 171590 )
$4921
-
$1248463
$0.57
-7.3 ( 7.3 )
$965
global institutional global industrial
$1900.50
-111.1 ( 111.1 )
$46.70
$22505
$94282
-7 ( 7 )
1.00% ( 1.00 % )
-1995 ( 1995 )
$2014
-19804 ( 19804 )
-3086 ( 3086 )
$1197
-639.2 ( 639.2 )
-1293 ( 1293 )
$7008
$373519
$208.30
$6
13% ( 13 % )
71% ( 71 % )
$140.39
$404
$41.31
$50.70
$494788
$17.23

<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?

March 10 2014
$5312
$704.40
-6 ( 6 )
$167.70
-458 ( 458 )
$6956
$85.82
35.0% ( 35.0 % )
$1002
$100.00
29% ( 29 % )
36% ( 36 % )
$77
$ -61.1 ( 61.1 )
$5549.00
$604
$4507
sq . ft. ( 1 )
$37.40
-11.9 ( 11.9 )
$819
3.932% ( 3.932 % )
$0.19
$396
-4472 ( 4472 )
$143
-22.4 ( 22.4 )
$78.50
$30741
$100
$1110.10
$ -599 ( 599 )
-2824 ( 2824 )
-1380 ( 1380 )
$185836
$24.70
8.2% ( 8.2 % )
$6221
$76676
-72.0 ( 72.0 )
$143.50
137% ( 137 % )
$195
-
$1033
$74.50
$1.20
-9.3 ( 9.3 )
$8066
-2381 ( 2381 )
$1859
$74.58
$106.30
-42.9 ( 42.9 )
$180.80
$43.60
$66085
-308.5 ( 308.5 )
$18733
$18086
$57645
$757.10
$54.12
$3430
$56.00
-
0.22% ( 0.22 % ) - 0.23% ( 0.23 % )
$2014
-21 ( 21 )
$20454
$127.08
$403.80
-200284 ( 200284 )
-42 ( 42 )
$7822
$27.50
-762466 ( 762466 )
4.17% ( 4.17 % ) - 4.40% ( 4.40 % )
17.3% ( 17.3 % )
-11239 ( 11239 )
$176.96
$1887
$80.56
-12.9 ( 12.9 )
$6179
$8.87
$100.00
$4036
-572 ( 572 )
$8.40
-19830 ( 19830 )
-37.0 ( 37.0 )
$1001
$188
-11 ( 11 )
-15101 ( 15101 )
-0.5 ( 0.5 )
-50540 ( 50540 )
-2 ( 2 )
-230786 ( 230786 )
-552 ( 552 )
3.2% ( 3.2 % )
Dec . 2015
$ -10332 ( 10332 )
$2220
29.60% ( 29.60 % )
$44.49
$204.57
$32136
$562
-25387 ( 25387 )
11.92% ( 11.92 % )
$29793
$120.00
$142.68
$0.40
86.2% ( 86.2 % )
-1413 ( 1413 )
-3565 ( 3565 )
$410047
$24.28
$455
$9.48
$20628
( in thousands )
-312 ( 312 )
nan
$169514
$64260
-29.6 ( 29.6 )
operating
$52.25
$163
-7140 ( 7140 )
$4131.70
$828084
$4373840
$1513.20
2.35% ( 2.35 % )
0.8% ( 0.8 % )
$201714
-1 ( 1 )
$5801
$237
$93.53
-5.6 ( 5.6 )
$1931.20
$175.04
$327.11
3.46% ( 3.46 % )
$143966
$216.20
$348
4.50% ( 4.50 % )
5.8% ( 5.8 % )
$294
-5.1 ( 5.1 )
$319.40
$ -29 ( 29 )
$16012
$4096
-240 ( 240 )
$40
high
-5 ( 5 )
$54.31
$912926
1.4% ( 1.4 % )
$1542
$148858924
$ -33774 ( 33774 )
$150
-121 ( 121 )
$446722
10% ( 10 % )
$1170
-1561 ( 1561 )
-17356 ( 17356 )
$27000
-126 ( 126 )
-
-12356 ( 12356 )
-130 ( 130 )
-
$75896
$ -28 ( 28 )
$227
$954377
-42451 ( 42451 )
-583.5 ( 583.5 )
-
$156.70
2.3% ( 2.3 % )
6 months
-407 ( 407 )
$157.90
$214112
$ -333601 ( 333601 )
$2.71
-3.0 ( 3.0 )
$19924
-161 ( 161 )
$6639
$673.00
$835
$2356
$2340
$35.01
170% ( 170 % )
$ -20681 ( 20681 )
$4042
-114 ( 114 )
$14123
-23.1 ( 23.1 )
$ -1.4 ( 1.4 )
$14215
actual
$20.25
-174.1 ( 174.1 )
-4 ( 4 )
$2014
$128
$31.60
$8.69
$28302
-2236 ( 2236 )
-5.7 ( 5.7 )
-26074 ( 26074 )
838 mw - boiling water
-7 ( 7 )
-828 ( 828 )
$724899
$663
$1279
$ -215 ( 215 )
-3240 ( 3240 )
$52083
$3339
-114 ( 114 )
$154.00
2.9% ( 2.9 % )
$ -35 ( 35 )
$1758
$3575.40
dominican republic
$101.10
$2529
2.75% ( 2.75 % )
$2811
$1544
-504.3 ( 504.3 )
-89 ( 89 )
$7963
$22.19
$1032
-8 ( 8 )
$1741
$11.50
-595 ( 595 )
-
-15 ( 15 )
$ -354400 ( 354400 )
$ -132.9 ( 132.9 )
$99
1.91% ( 1.91 % )
$615
( 1.0% ( 1.0 % ) )
$ 2.1 billion
$437
-7 ( 7 )
$108.58
$1277
-150 ( 150 )
$89923
$2424795
$231
$373
-431.1 ( 431.1 )
$ -3922 ( 3922 )
-3.0 ( 3.0 )
$2606546
$57
2.9% ( 2.9 % )
$997816
1.6% ( 1.6 % )
$427
-178 ( 178 )
$185.60
$647776
$ -108716 ( 108716 )
$4.35
$10110
$744
$20.74
-30849 ( 30849 )
$1018.60
$3842
global institutional global industrial
-13 ( 13 )
$9665
-19604 ( 19604 )
120% ( 120 % )
-141 ( 141 )
-1 ( 1 )
-1367 ( 1367 )
$2013
-61 ( 61 )
$100.00
$100.00
$751.80
$4916
$2.23
$284
37.14% ( 37.14 % )
-322 ( 322 )
$6184
$2500
$ -28711 ( 28711 )
$114.10
$97.33
-544 ( 544 )
$62.09
$568890
-85 ( 85 )
-4476 ( 4476 )
$63.79
-226493 ( 226493 )
$323.90
$ -6085 ( 6085 )
-0.6 ( 0.6 )
$122300000.00
$ -799 ( 799 )
$1733
-28 ( 28 )
$118
$491
9.7% ( 9.7 % )
$1667.20
$ -138.2 ( 138.2 )
$13.94
$887
-9 ( 9 )
-3633 ( 3633 )
-4.4 ( 4.4 )
$3.89
$100.00

<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<string>:1: SyntaxWarning: 'float' object is not callable; perhaps you missed a comma?

In [91]:
df.shape

(15970, 5)

In [92]:
for i, row in df.iterrows():
    if '[' in str(row['answer']) and ']' in str(row['answer']):
        df.drop(i, inplace=True)

In [93]:
df.shape

(15970, 5)

In [94]:
df.to_csv("../data/pseudo_json_dataset_V3_2048_without_list_answers.csv", index=False)

In [95]:
odf = pd.read_csv('../data/original_convfinqa_dataset.csv')
odf.head()

,html_content,questions
0,"<html>\n <body>\n ""distribution date"" ) . unt...",['what was the percentage of the total common ...
1,"<html>\n <body>\n ""three factor formula"" ) . ...","['in the year of 2013, during the second quart..."
2,"<html>\n <body>\n $ 25.7 million in cash , in...","['in the year of 2009, how much did the income..."
3,<html>\n <body>\n $ 43.3 million in 2011 comp...,['what was the difference between the net sale...
4,<html>\n <body>\n ( $ 125 million ) and highe...,['what were north american industrial packagin...

In [96]:
odf['index'] = odf.index + 1

In [97]:
odf[odf['index'] == 1]

,html_content,questions,index
0,"<html>\n <body>\n ""distribution date"" ) . unt...",['what was the percentage of the total common ...,1

In [98]:
def convert_html_to_json(html_content, index):
    # Parse HTML content
    soup = BeautifulSoup(html_content, 'html.parser')

    # Find the table
    table = soup.find('table')

    # Initialize an empty list to store table data
    table_data = []

    headers = True
    # Extract table data
    if index in indexes:
        headers = False
    rows = table.find_all('tr')
    for row_index, row in enumerate(rows):
        cols = row.find_all(['td'])[1:]
        if headers:
            if row_index == 0:
                headers = [col.text.strip() for col in cols]
            else:
                row_data = {}
                for i, (col, head) in enumerate(zip(cols, headers)):
                    if i == 0:
                        present_header = col.text.strip()
                        row_data[present_header] = {}
                    else:
                        row_data[present_header][head] = col.text.strip()
                table_data.append(row_data)
        else:
            row_data = {}
            for i, col in enumerate(cols):
                if i == 0:
                    present_header = col.text.strip()
                    row_data[present_header] = {}
                else:
                    row_data[present_header] = col.text.strip()
            table_data.append(row_data)

    # Convert list to JSON
    json_data = json.dumps(table_data, indent=4)

    # Print JSON data
    print(json_data)

In [99]:
json_data = convert_html_to_json(odf.loc[1, 'html_content'], odf.loc[1, "index"])

[
    {
        "sales and service revenues": {
            "year ended december 31 2013 1st qtr": "$ 1562",
            "year ended december 31 2013 2nd qtr": "$ 1683",
            "year ended december 31 2013 3rd qtr": "$ 1637",
            "year ended december 31 2013 4th qtr": "$ 1938"
        }
    },
    {
        "operating income ( loss )": {
            "year ended december 31 2013 1st qtr": "95",
            "year ended december 31 2013 2nd qtr": "116",
            "year ended december 31 2013 3rd qtr": "127",
            "year ended december 31 2013 4th qtr": "174"
        }
    },
    {
        "earnings ( loss ) before income taxes": {
            "year ended december 31 2013 1st qtr": "65",
            "year ended december 31 2013 2nd qtr": "87",
            "year ended december 31 2013 3rd qtr": "99",
            "year ended december 31 2013 4th qtr": "143"
        }
    },
    {
        "net earnings ( loss )": {
            "year ended december 31 2013 1st qtr": "44",
            "year ended december 31 2013 2nd qtr": "57",
            "year ended december 31 2013 3rd qtr": "69",
            "year ended december 31 2013 4th qtr": "91"
        }
    },
    {
        "dividends declared per share": {
            "year ended december 31 2013 1st qtr": "$ 0.10",
            "year ended december 31 2013 2nd qtr": "$ 0.10",
            "year ended december 31 2013 3rd qtr": "$ 0.10",
            "year ended december 31 2013 4th qtr": "$ 0.20"
        }
    },
    {
        "basic earnings ( loss ) per share": {
            "year ended december 31 2013 1st qtr": "$ 0.88",
            "year ended december 31 2013 2nd qtr": "$ 1.14",
            "year ended december 31 2013 3rd qtr": "$ 1.38",
            "year ended december 31 2013 4th qtr": "$ 1.86"
        }
    },
    {
        "diluted earnings ( loss ) per share": {
            "year ended december 31 2013 1st qtr": "$ 0.87",
            "year ended december 31 2013 2nd qtr": "$ 1.12",
            "year ended december 31 2013 3rd qtr": "$ 1.36",
            "year ended december 31 2013 4th qtr": "$ 1.82"
        }
    }
]

In [100]:
type(json_data)

NoneType

In [101]:
for i, row in df.iterrows():
    convert_to_json(row['html_content'], row['index'])
    break

TypeError: convert_to_json() missing 1 required positional argument: 'index'